/**
 * Estrutura de navegação da documentação do DataForge.
 *
 * Espelha a arquitetura de informação de uma documentação de linguagem madura:
 * uma introdução, uma visão geral progressiva, fundamentos, técnicas aplicadas,
 * a biblioteca padrão, as ferramentas, os exercícios e a referência formal.
 */

export type NavItem = {
  title: string;
  href: string;
  badge?: string;
};

export type NavSection = {
  title: string;
  items: NavItem[];
  /** Seções de item único aparecem como link direto, sem acordeão. */
  standalone?: boolean;
  badge?: string;
  /** Começa aberta na primeira visita. */
};

export const nav: NavSection[] = [
  {
    title: 'Introdução',
    standalone: true,
    items: [{ title: 'Introdução', href: '/docs' }],
  },
  {
    title: 'Visão geral',
    items: [
      { title: 'Primeiros passos', href: '/docs/primeiros-passos' },
      { title: 'Instalação', href: '/docs/instalacao' },
      { title: 'Docker', href: '/docs/instalacao/docker' },
      { title: 'Variáveis', href: '/docs/variaveis' },
      { title: 'Tipos', href: '/docs/tipos' },
      { title: 'Operadores', href: '/docs/operadores' },
      { title: 'Condicionais', href: '/docs/condicionais' },
      { title: 'Laços', href: '/docs/lacos' },
      { title: 'Coleções', href: '/docs/colecoes' },
      { title: 'Textos', href: '/docs/textos' },
      { title: 'Ações', href: '/docs/acoes' },
      { title: 'Blueprints', href: '/docs/blueprints' },
      { title: 'Tratamento de erros', href: '/docs/erros' },
      { title: 'Pipelines', href: '/docs/pipelines' },
      { title: 'Sistema de arquivos', href: '/docs/arquivos' },
      { title: 'O REPL', href: '/docs/repl' },
    ],
  },
  {
    title: 'Fundamentos',
    items: [
      { title: 'Anotações de tipo', href: '/docs/fundamentos/anotacoes-de-tipo' },
      { title: 'Records', href: '/docs/fundamentos/records' },
      { title: 'Enums', href: '/docs/fundamentos/enums' },
      { title: 'Pattern matching', href: '/docs/fundamentos/pattern-matching' },
      { title: 'Desestruturação', href: '/docs/fundamentos/desestruturacao' },
      { title: 'Spread e rest', href: '/docs/fundamentos/spread' },
      { title: 'Compreensões', href: '/docs/fundamentos/compreensoes' },
      { title: 'Interpolação', href: '/docs/fundamentos/interpolacao' },
      { title: 'Generators', href: '/docs/fundamentos/generators' },
      { title: 'Closures e lambdas', href: '/docs/fundamentos/closures' },
      { title: 'Decoradores', href: '/docs/fundamentos/decoradores' },
      { title: 'Decoradores avançados', href: '/docs/fundamentos/decoradores-avancados' },
      { title: 'Traits', href: '/docs/fundamentos/traits' },
      { title: 'Generics', href: '/docs/fundamentos/generics' },
      { title: 'Escopo', href: '/docs/fundamentos/escopo' },
      { title: 'Módulos', href: '/docs/fundamentos/modulos' },
      // O sistema de tipos morava num grupo próprio, e isso o punha a
      // oito seções de distância de 'Anotações de tipo', que é onde
      // quem procura por ele começa. Os títulos que colidiam com um
      // item já existente aqui foram desambiguados — dois 'Generics'
      // no mesmo menu não dizem qual é qual.
      { title: 'Sistema de tipos: visão geral', href: '/docs/tipos/visao-geral' },
      { title: 'Tipos nomeados', href: '/docs/tipos-nomeados' },
      { title: 'Tuplas', href: '/docs/tipos/tuplas' },
      { title: 'Resultado e Talvez', href: '/docs/tipos/resultado' },
      { title: 'Reflexão de tipos', href: '/docs/tipos/reflexao' },
      { title: 'Fundamentos e tipos: o mapa', href: '/docs/tipos/mapa' },
      { title: 'Generics: o sistema de tipos', href: '/docs/tipos/genericos' },
      { title: 'Sistema de traits', href: '/docs/tipos/traits' },
    ],
  },
  {
    title: 'Módulos e empacotamento',
    items: [
      { title: 'O sistema de módulos', href: '/docs/modulos' },
      { title: 'Resolução', href: '/docs/modulos/resolucao' },
      { title: 'Carga, ordem e ciclos', href: '/docs/modulos/carga' },
      { title: 'A superfície de um módulo', href: '/docs/modulos/superficie' },
      { title: 'Templates e visão', href: '/docs/modulos/templates' },
    ],
  },
  {
    title: 'Bibliotecas',
    items: [
      { title: 'Escrever uma biblioteca', href: '/docs/bibliotecas' },
      { title: 'Estrutura', href: '/docs/bibliotecas/estrutura' },
      { title: 'O contrato', href: '/docs/bibliotecas/contrato' },
      { title: 'Testes de biblioteca', href: '/docs/bibliotecas/testes' },
      { title: 'Versão e compatibilidade', href: '/docs/bibliotecas/versao' },
      { title: 'Publicar', href: '/docs/bibliotecas/publicar' },
      { title: 'Manter', href: '/docs/bibliotecas/manutencao' },
    ],
  },
  {
    title: 'Orientação a objetos',
    items: [
      { title: 'Visão geral', href: '/docs/oop' },
      { title: 'Fundamentos', href: '/docs/oop/fundamentos' },
      { title: 'Blueprints', href: '/docs/oop/blueprints' },
      { title: 'Campos e visibilidade', href: '/docs/oop/campos' },
      { title: 'Propriedades', href: '/docs/oop/propriedades' },
      { title: 'Métodos estáticos', href: '/docs/oop/estaticos' },
      { title: 'Sobrecarga de operadores', href: '/docs/oop/operadores' },
      { title: 'Métodos mágicos', href: '/docs/oop/magicos' },
      { title: 'slots', href: '/docs/oop/slots' },
      { title: 'Herança e traits', href: '/docs/oop/heranca' },
      { title: 'MRO — resolução', href: '/docs/oop/mro' },
      { title: 'Abstratos e contratos', href: '/docs/oop/abstratos' },
      { title: 'Encapsulamento', href: '/docs/oop/encapsulamento' },
      { title: 'Polimorfismo', href: '/docs/oop/polimorfismo' },
      { title: 'Relacionamentos', href: '/docs/oop/relacionamentos' },
      { title: 'Modificadores', href: '/docs/oop/modificadores' },
      { title: 'Contratos', href: '/docs/oop/contratos' },
      { title: 'Sobrecarga', href: '/docs/oop/sobrecarga' },
      { title: 'Metaclasses', href: '/docs/oop/metaclasses' },
      { title: 'augment', href: '/docs/oop/augment' },
      { title: 'Reflexão', href: '/docs/oop/reflexao' },
      { title: 'Cópia, imutabilidade e serialização', href: '/docs/oop/objetos' },
      { title: 'Injeção de dependência', href: '/docs/oop/injecao' },
      { title: 'Padrões de projeto', href: '/docs/oop/padroes' },
      { title: 'Ciclo de vida e memória', href: '/docs/oop/memoria' },
      { title: 'Métricas e cheiros', href: '/docs/oop/metricas' },
      { title: 'SOLID', href: '/docs/oop/solid' },
      { title: 'Modelagem', href: '/docs/oop/modelagem' },
      // Metaprogramação vinha num grupo próprio, longe de 'Metaclasses'
      // e 'Reflexão' — que são a porta de entrada dela e vivem aqui.
      { title: 'comptime', href: '/docs/metaprogramacao/comptime' },
      { title: 'Macros', href: '/docs/metaprogramacao/macros' },
      { title: 'DSLs', href: '/docs/metaprogramacao/dsl' },
      { title: 'Plugins do check', href: '/docs/metaprogramacao/plugins' },
      { title: 'Metaprogramação: o mapa', href: '/docs/metaprogramacao/mapa' },
    ],
  },
  {
    title: 'Banco de dados',
    items: [
      { title: 'Forge — visão geral', href: '/docs/banco-de-dados' },
      { title: 'Construtor de consultas', href: '/docs/banco-de-dados/consultas' },
      { title: 'Transações e pool', href: '/docs/banco-de-dados/transacoes' },
      { title: 'Cada motor', href: '/docs/banco-de-dados/motores' },
      { title: 'ORM', href: '/docs/orm' },
      { title: 'Relações', href: '/docs/orm/relacoes' },
      { title: 'Migrações', href: '/docs/orm/migracoes' },
    ],
  },
  {
    title: 'Dados, ETL e SQLite',
    items: [
      { title: 'Análise de dados', href: '/docs/dados' },
      { title: 'Quadro — a tabela', href: '/docs/dados/quadro' },
      { title: 'Os verbos do pipeline', href: '/docs/dados/verbos' },
      { title: 'ETL', href: '/docs/dados/etl' },
      { title: 'Qualidade de dados', href: '/docs/dados/qualidade' },
      { title: 'SQLite', href: '/docs/sqlite' },
      { title: 'O mapa do ecossistema', href: '/docs/dados/mapa' },
      { title: 'Data Lake', href: '/docs/tecnicas/lago' },
      { title: 'Parquet', href: '/docs/tecnicas/parquet' },
      { title: 'Aprendizado de máquina', href: '/docs/tecnicas/ml' },
    ],
  },
  {
    title: 'Crucible — testes',
    items: [
      { title: 'Testes: visão geral', href: '/docs/testes' },
      { title: 'Crucible', href: '/docs/crucible' },
      { title: 'Os matchers', href: '/docs/crucible/matchers' },
      { title: 'Fixtures e ganchos', href: '/docs/crucible/fixtures' },
      { title: 'Dublês', href: '/docs/crucible/dubles' },
      { title: 'Teste por propriedade', href: '/docs/crucible/propriedades' },
      { title: 'Relatórios e CI', href: '/docs/crucible/relatorios' },
      { title: 'Cenários', href: '/docs/crucible/cenarios' },
      { title: 'Contratos e mutação', href: '/docs/crucible/mutacao' },
    ],
  },
  {
    title: 'Complexidade',
    items: [
      { title: 'Big-O', href: '/docs/big-o' },
      { title: 'As classes', href: '/docs/big-o/classes' },
      { title: 'Analisar o seu código', href: '/docs/big-o/analisar' },
      { title: 'Padrões e como melhorar', href: '/docs/big-o/padroes' },
      { title: 'Custo das estruturas', href: '/docs/big-o/estruturas' },
      { title: 'Melhor, médio e pior', href: '/docs/big-o/casos' },
      { title: 'Complexidade de espaço', href: '/docs/big-o/espaco' },
      { title: 'Recorrências e Teorema Mestre', href: '/docs/big-o/recorrencias' },
      { title: 'Análise amortizada', href: '/docs/big-o/amortizada' },
      { title: 'Ω, Θ e limites inferiores', href: '/docs/big-o/limites' },
      { title: 'Estruturas avançadas', href: '/docs/big-o/estruturas-avancadas' },
      { title: 'Complexidade em paralelo', href: '/docs/big-o/paralelo' },
      { title: 'A constante que decide', href: '/docs/big-o/constantes' },
      { title: 'Complexidade em dados e I/O', href: '/docs/big-o/dados' },
    ],
  },
  {
    title: 'Kiln — framework web',
    items: [
      { title: 'APIs: REST e RESTful', href: '/docs/api' },
      { title: 'Visão geral', href: '/docs/kiln' },
      { title: 'Rotas e parâmetros', href: '/docs/kiln/rotas' },
      { title: 'Respostas', href: '/docs/kiln/respostas' },
      { title: 'Páginas HTML', href: '/docs/kiln/paginas' },
      { title: 'Middleware', href: '/docs/kiln/middleware' },
      { title: 'Sessão e cookies', href: '/docs/kiln/sessao' },
      { title: 'Arquivos estáticos', href: '/docs/kiln/estaticos' },
      { title: 'Receber arquivos', href: '/docs/kiln/uploads' },
      { title: 'Tempo real', href: '/docs/kiln/tempo-real' },
      { title: 'Levar para produção', href: '/docs/kiln/producao' },
      { title: 'Referência', href: '/docs/kiln/referencia' },
    ],
  },
  {
    title: 'Telegram — bots',
    items: [
      { title: 'Visão geral', href: '/docs/telegram' },
      { title: 'Comandos e roteamento', href: '/docs/telegram/comandos' },
      { title: 'Teclados e formatação', href: '/docs/telegram/teclados' },
      { title: 'Conversas e estado', href: '/docs/telegram/conversas' },
      { title: 'Mídia, arquivos e grupos', href: '/docs/telegram/midia' },
      { title: 'Testar sem rede', href: '/docs/telegram/testes' },
      { title: 'Publicar o bot', href: '/docs/telegram/publicar' },
    ],
  },
  {
    title: 'Domínio e DDD',
    items: [
      { title: 'Visão geral', href: '/docs/dominio' },
      { title: 'Valores e entidades', href: '/docs/dominio/valores' },
      { title: 'Agregados e invariantes', href: '/docs/dominio/agregados' },
      { title: 'Eventos e unidade de trabalho', href: '/docs/dominio/eventos' },
      { title: 'Regras e contextos', href: '/docs/dominio/contextos' },
    ],
  },
  {
    title: 'Estruturas e ponteiros',
    items: [
      { title: 'Visão geral', href: '/docs/estruturas' },
      { title: 'Blocos e janelas', href: '/docs/estruturas/janelas' },
      { title: 'Ponteiros', href: '/docs/estruturas/ponteiros' },
    ],
  },
  {
    title: 'Reativo',
    items: [
      { title: 'Visão geral', href: '/docs/reativo' },
      { title: 'Sinais e derivados', href: '/docs/reativo/sinais' },
      { title: 'Efeitos e propagação', href: '/docs/reativo/efeitos' },
      { title: 'Observáveis', href: '/docs/reativo/observaveis' },
    ],
  },
  {
    title: 'Vitrine — dashboards',
    items: [
      { title: 'Visão geral', href: '/docs/vitrine' },
      { title: 'Componentes', href: '/docs/vitrine/componentes' },
      { title: 'Painel profissional', href: '/docs/vitrine/painel' },
      { title: 'Layout', href: '/docs/vitrine/layout' },
      { title: 'Estado e cache', href: '/docs/vitrine/estado' },
      { title: 'Gráficos', href: '/docs/vitrine/graficos' },
      { title: 'Páginas e segurança', href: '/docs/vitrine/paginas' },
      { title: 'Acessibilidade e idioma', href: '/docs/vitrine/acessibilidade' },
      { title: 'Testar sem navegador', href: '/docs/vitrine/testes' },
      { title: 'Produção', href: '/docs/vitrine/producao' },
      { title: 'Um projeto completo', href: '/docs/vitrine/projeto' },
      { title: 'Referência', href: '/docs/vitrine/referencia' },
    ],
  },
  {
    title: 'FFI e nativo',
    items: [
      { title: 'Chamar C', href: '/docs/ffi/c' },
      { title: 'Ponteiros e memória crua', href: '/docs/ffi/ponteiros' },
      { title: 'Callbacks', href: '/docs/ffi/callbacks' },
      { title: 'FFI: o mapa', href: '/docs/ffi/mapa' },
    ],
  },
  {
    title: 'Dentro do compilador',
    items: [
      { title: 'O caminho de compilação', href: '/docs/compilador/pipeline' },
      { title: 'HIR — a árvore sem açúcar', href: '/docs/compilador/hir' },
      { title: 'MIR — o grafo de fluxo', href: '/docs/compilador/mir' },
      { title: 'O que o fluxo prova', href: '/docs/compilador/analises' },
      { title: 'SSA e o nó φ', href: '/docs/compilador/ssa' },
      { title: 'Otimização, medida', href: '/docs/compilador/otimizacao' },
      { title: 'O backend, e o que não é', href: '/docs/compilador/backend' },
      { title: 'O compilador: o mapa', href: '/docs/compilador/mapa' },
      { title: 'Backend: o mapa', href: '/docs/compilador/mapa-backend' },
    ],
  },
  {
    title: 'Runtime e laço de eventos',
    items: [
      { title: 'O laço de eventos', href: '/docs/runtime/laco' },
      { title: 'O escalonador', href: '/docs/runtime/escalonador' },
      { title: 'Fibras', href: '/docs/runtime/fibras' },
      { title: 'O runtime: o mapa', href: '/docs/runtime/mapa' },
    ],
  },
  {
    title: 'Observabilidade e memória',
    items: [
      { title: 'Percentis, e a cauda', href: '/docs/observabilidade/perfil' },
      { title: 'A diferença é real?', href: '/docs/observabilidade/comparar' },
      { title: 'Flame graph e pausas', href: '/docs/observabilidade/chamadas' },
      { title: 'O coletor sob controle', href: '/docs/memoria/coletor' },
      { title: 'Observabilidade: o mapa', href: '/docs/observabilidade/mapa' },
    ],
  },
  {
    title: 'Partida e segurança',
    items: [
      { title: 'Antes da primeira linha', href: '/docs/partida/inicio' },
      { title: 'Uma variável por thread', href: '/docs/partida/por-thread' },
      { title: 'A pilha', href: '/docs/partida/pilha' },
      { title: 'Fronteira de capacidade', href: '/docs/seguranca/capacidade' },
      { title: 'Partida e segurança: o mapa', href: '/docs/partida/mapa' },
      { title: 'Hardware: o mapa', href: '/docs/hardware/mapa' },
    ],
  },
  {
    title: 'Superfície e alvos',
    items: [
      { title: 'A superfície é o contrato', href: '/docs/abi/superficie' },
      { title: 'O que quebra', href: '/docs/abi/compatibilidade' },
      { title: 'O mapa de símbolos', href: '/docs/abi/simbolos' },
      { title: 'Onde este programa roda', href: '/docs/alvos/portabilidade' },
      { title: 'WebAssembly, com precisão', href: '/docs/alvos/wasm' },
      { title: 'ABI e alvos: o mapa', href: '/docs/abi/mapa' },
    ],
  },
  {
    title: 'Ecossistema e design',
    items: [
      { title: 'O ecossistema, conferido', href: '/docs/ecossistema/componentes' },
      { title: 'O que não existe', href: '/docs/ecossistema/ausencias' },
      { title: 'Os dez princípios', href: '/docs/ecossistema/principios' },
      { title: 'As tensões', href: '/docs/ecossistema/tensoes' },
      { title: 'Onde o tempo vai', href: '/docs/ecossistema/percurso' },
      { title: 'Referência rápida', href: '/docs/ecossistema/referencia' },
      { title: 'Ecossistema: o mapa', href: '/docs/ecossistema/mapa' },
    ],
  },
  {
    title: 'Concorrência avançada',
    items: [
      { title: 'Memória transacional', href: '/docs/concorrencia/stm' },
      { title: 'Atômicos e sem trava', href: '/docs/concorrencia/sem-trava' },
      { title: 'Concorrência: o mapa', href: '/docs/concorrencia/mapa' },
    ],
  },
  {
    title: 'Memória e recursos',
    items: [
      { title: 'Posse e empréstimo', href: '/docs/memoria/posse' },
      { title: 'Escopo de recursos', href: '/docs/memoria/escopo' },
      { title: 'Memória e layout', href: '/docs/memoria/layout' },
      { title: 'Memória determinística: o mapa', href: '/docs/memoria/mapa' },
    ],
  },
  {
    title: 'Lavra — consulta',
    items: [
      { title: 'Visão geral', href: '/docs/lavra' },
      { title: 'O esquema', href: '/docs/lavra/esquema' },
      { title: 'A consulta', href: '/docs/lavra/consulta' },
      { title: 'Resolvedores', href: '/docs/lavra/resolvedores' },
      { title: 'Desempenho', href: '/docs/lavra/desempenho' },
      { title: 'Segurança', href: '/docs/lavra/seguranca' },
      { title: 'O servidor', href: '/docs/lavra/servidor' },
      { title: 'Federação', href: '/docs/lavra/federacao' },
      { title: 'Na prática', href: '/docs/lavra/pratica' },
    ],
  },
  {
    title: 'Técnicas',
    items: [
      { title: 'Análise estática', href: '/docs/tecnicas/analise-estatica' },
      { title: 'Testes', href: '/docs/tecnicas/testes' },
      { title: 'Cobertura', href: '/docs/tecnicas/cobertura' },
      { title: 'Instantâneos e isolamento', href: '/docs/tecnicas/instantaneos' },
      { title: 'Formatação', href: '/docs/tecnicas/formatacao' },
      { title: 'Lint', href: '/docs/tecnicas/lint' },
      { title: 'Documentação', href: '/docs/tecnicas/documentacao' },
      { title: 'Estrutura de projeto', href: '/docs/tecnicas/projeto' },
      { title: 'Concorrência', href: '/docs/tecnicas/concorrencia' },
      { title: 'Benchmark', href: '/docs/tecnicas/bench' },
      { title: 'Streams', href: '/docs/tecnicas/streams' },
      { title: 'Serialização', href: '/docs/tecnicas/serializacao' },
      { title: 'Arquivos', href: '/docs/tecnicas/arquivos' },
      { title: 'Banco de dados', href: '/docs/tecnicas/banco-de-dados' },
      { title: 'CRUD completo', href: '/docs/tecnicas/banco-de-dados/crud' },
      { title: 'Relatórios e busca', href: '/docs/tecnicas/banco-de-dados/relatorios' },
      { title: 'Migrações', href: '/docs/tecnicas/banco-de-dados/migracoes' },
      { title: 'Pipelines e orquestração', href: '/docs/tecnicas/pipeline' },
      { title: 'Qualidade de dados', href: '/docs/tecnicas/qualidade' },
      { title: 'Parquet', href: '/docs/tecnicas/parquet' },
      { title: 'Data Lake', href: '/docs/tecnicas/lago' },
      { title: 'Aprendizado de máquina', href: '/docs/tecnicas/ml' },
      { title: 'Streaming', href: '/docs/tecnicas/streaming' },
      { title: 'Observabilidade e linhagem', href: '/docs/tecnicas/observar' },
      { title: 'Planilhas', href: '/docs/tecnicas/planilhas' },
      { title: 'Microserviços', href: '/docs/tecnicas/microservicos' },
      { title: 'OpenAPI, Insomnia e Postman', href: '/docs/tecnicas/api' },
      { title: 'Servidor HTTP', href: '/docs/tecnicas/http' },
      { title: 'Editor e extensão', href: '/docs/editor' },
      { title: 'Servidor de linguagem (LSP)', href: '/docs/tecnicas/lsp' },
      { title: 'Logging', href: '/docs/tecnicas/logging' },
      { title: 'Datas e horas', href: '/docs/tecnicas/datas' },
      { title: 'Processos', href: '/docs/tecnicas/processos' },
      { title: 'Criptografia', href: '/docs/tecnicas/criptografia' },
      { title: 'Número exato (Decimal)', href: '/docs/tecnicas/decimal' },
      { title: 'A ponte para o Python', href: '/docs/tecnicas/ponte' },
    ],
  },
  {
    title: 'DevOps e produção',
    items: [
      { title: 'Visão geral', href: '/docs/devops' },
      { title: 'A imagem oficial', href: '/docs/instalacao/docker' },
      { title: 'Observabilidade', href: '/docs/tecnicas/observar' },
      { title: 'Segurança', href: '/docs/seguranca' },
      { title: 'Vitrine em produção', href: '/docs/vitrine/producao' },
      { title: 'Kiln em produção', href: '/docs/kiln/producao' },
    ],
  },
  {
    title: 'Biblioteca Arcane',
    items: [
      { title: 'Visão geral', href: '/docs/biblioteca' },
      { title: 'Arcane.API', href: '/docs/biblioteca/api' },
      { title: 'Arcane.Abi', href: '/docs/biblioteca/abi' },
      { title: 'Arcane.Alvo', href: '/docs/biblioteca/alvo' },
      { title: 'Arcane.Analytics', href: '/docs/biblioteca/analytics' },
      { title: 'Arcane.Archive', href: '/docs/biblioteca/archive' },
      { title: 'Arcane.Async', href: '/docs/biblioteca/async' },
      { title: 'Arcane.Bench', href: '/docs/biblioteca/bench' },
      { title: 'Arcane.Bytes', href: '/docs/biblioteca/bytes' },
      { title: 'Arcane.C', href: '/docs/biblioteca/c' },
      { title: 'Arcane.Capacidade', href: '/docs/biblioteca/capacidade' },
      { title: 'Arcane.Chaves', href: '/docs/biblioteca/chaves' },
      { title: 'Arcane.Cli', href: '/docs/biblioteca/cli' },
      { title: 'Arcane.Collections', href: '/docs/biblioteca/collections' },
      { title: 'Arcane.Color', href: '/docs/biblioteca/color' },
      { title: 'Arcane.Compilador', href: '/docs/biblioteca/compilador' },
      { title: 'Arcane.Concurrent', href: '/docs/biblioteca/concurrent' },
      { title: 'Arcane.Cortex', href: '/docs/biblioteca/cortex' },
      { title: 'Arcane.Crucible', href: '/docs/biblioteca/crucible' },
      { title: 'Arcane.Crypto', href: '/docs/biblioteca/crypto' },
      { title: 'Arcane.Data', href: '/docs/biblioteca/data' },
      { title: 'Arcane.Database', href: '/docs/biblioteca/database' },
      { title: 'Arcane.Decimal', href: '/docs/biblioteca/decimal' },
      { title: 'Arcane.Deteccao', href: '/docs/biblioteca/deteccao' },
      { title: 'Arcane.Dominio', href: '/docs/biblioteca/dominio' },
      { title: 'Arcane.Dsl', href: '/docs/biblioteca/dsl' },
      { title: 'Arcane.Ecossistema', href: '/docs/biblioteca/ecossistema' },
      { title: 'Arcane.Email', href: '/docs/biblioteca/email' },
      { title: 'Arcane.Estrutura', href: '/docs/biblioteca/estrutura' },
      { title: 'Arcane.Eventos', href: '/docs/biblioteca/eventos' },
      { title: 'Arcane.Excel', href: '/docs/biblioteca/excel' },
      { title: 'Arcane.Forge', href: '/docs/biblioteca/forge' },
      { title: 'Arcane.Functional', href: '/docs/biblioteca/functional' },
      { title: 'Arcane.Html', href: '/docs/biblioteca/html' },
      { title: 'Arcane.Http', href: '/docs/biblioteca/http' },
      { title: 'Arcane.IO', href: '/docs/biblioteca/io' },
      { title: 'Arcane.Inicio', href: '/docs/biblioteca/inicio' },
      { title: 'Arcane.Injecao', href: '/docs/biblioteca/injecao' },
      { title: 'Arcane.Iter', href: '/docs/biblioteca/iter' },
      { title: 'Arcane.Laco', href: '/docs/biblioteca/laco' },
      { title: 'Arcane.Lago', href: '/docs/biblioteca/lago' },
      { title: 'Arcane.Lavra', href: '/docs/biblioteca/lavra' },
      { title: 'Arcane.Logging', href: '/docs/biblioteca/logging' },
      { title: 'Arcane.Macro', href: '/docs/biblioteca/macro' },
      { title: 'Arcane.Malha', href: '/docs/biblioteca/malha' },
      { title: 'Arcane.Math', href: '/docs/biblioteca/math' },
      { title: 'Arcane.Memoria', href: '/docs/biblioteca/memoria' },
      { title: 'Arcane.Meta', href: '/docs/biblioteca/meta' },
      { title: 'Arcane.OS', href: '/docs/biblioteca/os' },
      { title: 'Arcane.Objetos', href: '/docs/biblioteca/objetos' },
      { title: 'Arcane.Observar', href: '/docs/biblioteca/observar' },
      { title: 'Arcane.Padroes', href: '/docs/biblioteca/padroes' },
      { title: 'Arcane.Percurso', href: '/docs/biblioteca/percurso' },
      { title: 'Arcane.Perfil', href: '/docs/biblioteca/perfil' },
      { title: 'Arcane.Pipeline', href: '/docs/biblioteca/pipeline' },
      { title: 'Arcane.Politica', href: '/docs/biblioteca/politica' },
      { title: 'Arcane.Ponte', href: '/docs/biblioteca/ponte' },
      { title: 'Arcane.Posse', href: '/docs/biblioteca/posse' },
      { title: 'Arcane.Principios', href: '/docs/biblioteca/principios' },
      { title: 'Arcane.Process', href: '/docs/biblioteca/process' },
      { title: 'Arcane.Quadro', href: '/docs/biblioteca/quadro' },
      { title: 'Arcane.Qualidade', href: '/docs/biblioteca/qualidade' },
      { title: 'Arcane.Reativo', href: '/docs/biblioteca/reativo' },
      { title: 'Arcane.Rede', href: '/docs/biblioteca/rede' },
      { title: 'Arcane.Reflexo', href: '/docs/biblioteca/reflexo' },
      { title: 'Arcane.Regex', href: '/docs/biblioteca/regex' },
      { title: 'Arcane.Resultado', href: '/docs/biblioteca/resultado' },
      { title: 'Arcane.Seguranca', href: '/docs/biblioteca/seguranca' },
      { title: 'Arcane.Serialization', href: '/docs/biblioteca/serialization' },
      { title: 'Arcane.Stm', href: '/docs/biblioteca/stm' },
      { title: 'Arcane.Stream', href: '/docs/biblioteca/stream' },
      { title: 'Arcane.Telegram', href: '/docs/biblioteca/telegram' },
      { title: 'Arcane.Test', href: '/docs/biblioteca/test' },
      { title: 'Arcane.Text', href: '/docs/biblioteca/text' },
      { title: 'Arcane.Time', href: '/docs/biblioteca/time' },
      { title: 'Arcane.Tipos', href: '/docs/biblioteca/tipos' },
      { title: 'Arcane.Url', href: '/docs/biblioteca/url' },
      { title: 'Arcane.Web', href: '/docs/biblioteca/web' },
    ],
  },
  {
    title: 'CLI',
    items: [
      { title: 'Visão geral', href: '/docs/cli' },
      { title: 'dataforge run', href: '/docs/cli/run' },
      { title: 'dataforge check', href: '/docs/cli/check' },
      { title: 'dataforge test', href: '/docs/cli/test' },
      { title: 'dataforge fmt', href: '/docs/cli/fmt' },
      { title: 'dataforge lint', href: '/docs/cli/lint' },
      { title: 'dataforge doc', href: '/docs/cli/doc' },
      { title: 'dataforge init', href: '/docs/cli/init' },
      { title: 'dataforge repl', href: '/docs/cli/repl' },
      { title: 'dataforge add', href: '/docs/cli/pacotes' },
      { title: 'dataforge watch', href: '/docs/cli/watch' },
      { title: 'dataforge bench', href: '/docs/cli/bench' },
      { title: 'dataforge explain', href: '/docs/cli/explain' },
      { title: 'dataforge editor', href: '/docs/cli/editor' },
      { title: 'forge.toml', href: '/docs/cli/forge-toml' },
    ],
  },
  {
    title: 'Exercícios',
    items: [
      { title: 'Visão geral', href: '/docs/exercicios' },
      { title: 'Fundamentos', href: '/docs/exercicios/01-fundamentos' },
      { title: 'Controle de fluxo', href: '/docs/exercicios/02-controle-fluxo' },
      { title: 'Coleções', href: '/docs/exercicios/03-colecoes' },
      { title: 'Textos', href: '/docs/exercicios/04-strings' },
      { title: 'Ações', href: '/docs/exercicios/05-acoes' },
      { title: 'Blueprints', href: '/docs/exercicios/06-blueprints' },
      { title: 'Erros', href: '/docs/exercicios/07-erros' },
      { title: 'Pipelines', href: '/docs/exercicios/08-pipelines' },
      { title: 'Módulos', href: '/docs/exercicios/09-modulos' },
      { title: 'Avançado', href: '/docs/exercicios/10-avancado' },
      { title: 'Tipos e checagem', href: '/docs/exercicios/11-tipos-e-checagem' },
      { title: 'Records e enums', href: '/docs/exercicios/12-records-e-enums' },
      { title: 'Desestruturação', href: '/docs/exercicios/13-desestruturacao' },
      { title: 'Pattern matching', href: '/docs/exercicios/14-pattern-matching' },
      { title: 'Streams', href: '/docs/exercicios/15-streams-e-generators' },
      { title: 'Módulos e projetos', href: '/docs/exercicios/16-modulos-e-projetos' },
      { title: 'Tempo e sistema', href: '/docs/exercicios/17-tempo-e-sistema' },
      { title: 'Persistência', href: '/docs/exercicios/18-dados-e-persistencia' },
      { title: 'Concorrência', href: '/docs/exercicios/19-concorrencia' },
      { title: 'Projetos finais', href: '/docs/exercicios/20-projetos-finais' },
      { title: 'OOP avançado', href: '/docs/exercicios/21-oop-avancado' },
      { title: 'Web com Kiln', href: '/docs/exercicios/22-web-kiln' },
      { title: 'Dados e planilhas', href: '/docs/exercicios/23-dados-e-planilhas' },
      { title: 'Banco de dados', href: '/docs/exercicios/24-banco-de-dados' },
      { title: 'Testes com Crucible', href: '/docs/exercicios/25-testes-crucible' },
      { title: 'Complexidade', href: '/docs/exercicios/26-complexidade' },
      { title: 'Ponte para o Python', href: '/docs/exercicios/27-ponte-python' },
      { title: 'Vitrine', href: '/docs/exercicios/28-vitrine' },
      { title: 'Banco e CRUD', href: '/docs/exercicios/29-banco-e-crud' },
      { title: 'Tempo real', href: '/docs/exercicios/30-tempo-real' },
      { title: 'Qualidade', href: '/docs/exercicios/31-qualidade' },
      { title: 'Microserviços', href: '/docs/exercicios/32-microservicos' },
      { title: 'Lavra', href: '/docs/exercicios/33-lavra' },
      { title: 'Binário e rede', href: '/docs/exercicios/34-binario-e-rede' },
      { title: 'Paralelismo', href: '/docs/exercicios/35-paralelismo' },
      { title: 'Quadro e dados', href: '/docs/exercicios/36-quadro-e-dados' },
      { title: 'OOP como sistema', href: '/docs/exercicios/37-oop-sistema' },
      { title: 'Sistema de tipos', href: '/docs/exercicios/38-tipos' },
      { title: 'Concorrência avançada', href: '/docs/exercicios/39-concorrencia-avancada' },
      { title: 'Metaprogramação', href: '/docs/exercicios/40-metaprogramacao' },
      { title: 'FFI e nativo', href: '/docs/exercicios/41-ffi-nativo' },
      { title: 'Dentro do compilador', href: '/docs/exercicios/42-compilador' },
      { title: 'Backend e otimização', href: '/docs/exercicios/43-backend' },
      { title: 'Runtime e laço de eventos', href: '/docs/exercicios/44-runtime' },
      { title: 'Observabilidade e memória', href: '/docs/exercicios/45-observabilidade' },
      { title: 'Partida, pilha e capacidade', href: '/docs/exercicios/46-partida' },
      { title: 'Superfície e alvos', href: '/docs/exercicios/47-abi-e-alvos' },
      { title: 'Ecossistema e design', href: '/docs/exercicios/48-ecossistema' },
      { title: 'Decimal exato e padrões', href: '/docs/exercicios/49-decimal-e-padroes' },
      { title: 'Domínio e DDD', href: '/docs/exercicios/50-dominio' },
      { title: 'Programação reativa', href: '/docs/exercicios/51-reativo' },
      { title: 'Estruturas e ponteiros', href: '/docs/exercicios/52-estruturas' },
      { title: 'Regex avançado', href: '/docs/exercicios/53-regex-avancado' },
      { title: 'Erros e famílias', href: '/docs/exercicios/54-erros' },
      { title: 'Métodos mágicos', href: '/docs/exercicios/55-oop-magicos' },
      { title: 'Bots de Telegram', href: '/docs/exercicios/56-telegram' },
      { title: 'Vitrine — o painel', href: '/docs/exercicios/57-vitrine-painel' },
    ],
  },
  {
    title: 'Pacotes',
    items: [
      { title: 'Gerenciador de pacotes', href: '/docs/pacotes' },
      { title: 'Versões lado a lado', href: '/docs/cli/versoes' },
      { title: 'Workspace', href: '/docs/cli/workspace' },
      { title: 'O cache de árvores', href: '/docs/cli/cache' },
      { title: 'Importar módulos', href: '/docs/pacotes/importar' },
      { title: 'Escrever uma biblioteca', href: '/docs/pacotes/escrever' },
      { title: 'Publicar um pacote', href: '/docs/pacotes/publicar' },
      { title: 'aleatorio', href: '/docs/pacotes/aleatorio' },
      { title: 'argumentos', href: '/docs/pacotes/argumentos' },
      { title: 'cache', href: '/docs/pacotes/cache' },
      { title: 'cofre', href: '/docs/pacotes/cofre' },
      { title: 'colecao', href: '/docs/pacotes/colecao' },
      { title: 'datas', href: '/docs/pacotes/datas' },
      { title: 'documento', href: '/docs/pacotes/documento' },
      { title: 'estado', href: '/docs/pacotes/estado' },
      { title: 'estatistica', href: '/docs/pacotes/estatistica' },
      { title: 'evento', href: '/docs/pacotes/evento' },
      { title: 'grafo', href: '/docs/pacotes/grafo' },
      { title: 'medida', href: '/docs/pacotes/medida' },
      { title: 'modelo', href: '/docs/pacotes/modelo' },
      { title: 'moeda', href: '/docs/pacotes/moeda' },
      { title: 'progresso', href: '/docs/pacotes/progresso' },
      { title: 'registro', href: '/docs/pacotes/registro' },
      { title: 'tentativa', href: '/docs/pacotes/tentativa' },
      { title: 'texto', href: '/docs/pacotes/texto' },
      { title: 'validador', href: '/docs/pacotes/validador' },
      { title: 'tabela', href: '/docs/pacotes/tabela' },
    ],
  },
  {
    title: 'Projetos',
    items: [
      { title: 'Visão geral', href: '/docs/projetos' },
      { title: 'Gestor de tarefas', href: '/docs/projetos/gestor-tarefas' },
      { title: 'Análise de vendas', href: '/docs/projetos/analise-vendas' },
      { title: 'API de links', href: '/docs/projetos/api-links' },
    ],
  },
  {
    title: 'Referência',
    items: [
      { title: 'Gramática (EBNF)', href: '/docs/referencia/gramatica' },
      { title: 'Palavras reservadas', href: '/docs/referencia/palavras-reservadas' },
      { title: 'Operadores', href: '/docs/referencia/operadores' },
      { title: 'Precedência', href: '/docs/referencia/precedencia' },
      { title: 'Sistema de tipos', href: '/docs/referencia/tipos' },
      { title: 'Hierarquia de erros', href: '/docs/referencia/erros' },
      { title: 'Funções embutidas', href: '/docs/referencia/embutidas' },
      { title: 'A máquina: como um .df executa', href: '/docs/vm' },
      { title: 'Arquitetura do runtime', href: '/docs/referencia/arquitetura' },
      { title: 'API pública (JSON)', href: '/api' },
    ],
  },
  {
    title: 'Receitas',
    items: [
      { title: 'Ferramenta de linha de comando', href: '/docs/receitas/cli' },
      { title: 'API REST', href: '/docs/receitas/api-rest' },
      { title: 'Pipeline ETL', href: '/docs/receitas/etl' },
      { title: 'Análise de dados', href: '/docs/receitas/analise-de-dados' },
      { title: 'Interpretador de expressões', href: '/docs/receitas/interpretador' },
      { title: 'Validadores brasileiros', href: '/docs/receitas/validadores' },
      { title: 'Fila de trabalho', href: '/docs/receitas/fila-de-trabalho' },
      { title: 'Máquina de estados', href: '/docs/receitas/maquina-de-estados' },
      { title: 'Processamento de CSV', href: '/docs/receitas/csv' },
      { title: 'Sistema de inventário', href: '/docs/receitas/inventario' },
    ],
  },
  {
    title: 'FAQ',
    items: [
      { title: 'Perguntas frequentes', href: '/docs/faq' },
      { title: 'Erros comuns', href: '/docs/faq/erros-comuns' },
      { title: 'Desempenho', href: '/docs/faq/desempenho' },
      { title: 'Comparação com Python', href: '/docs/faq/python' },
      { title: 'Comparação com JavaScript', href: '/docs/faq/javascript' },
      { title: 'Migração 3.x → 4.0', href: '/docs/faq/migracao' },
    ],
  },
  {
    title: 'Versões',
    standalone: true,
    items: [{ title: 'Versões', href: '/docs/versoes' }],
  },
  {
    title: 'Segurança da informação',
    items: [
      { title: 'O mapa', href: '/docs/seguranca/mapa' },
      { title: 'Princípios', href: '/docs/seguranca/principios' },
      { title: 'Ameaças e risco', href: '/docs/seguranca/ameacas' },
      { title: 'O que a linguagem garante', href: '/docs/seguranca/linguagem' },
      { title: 'Entrada e saída', href: '/docs/seguranca/entrada' },
      { title: 'Autenticação', href: '/docs/seguranca/autenticacao' },
      { title: 'Autorização e capacidades', href: '/docs/seguranca/autorizacao' },
      { title: 'Ataques a credenciais', href: '/docs/seguranca/ataques' },
      { title: 'As ferramentas', href: '/docs/seguranca/ferramentas' },
      { title: 'Criptografia e chaves', href: '/docs/seguranca/criptografia' },
      { title: 'Detecção e resposta', href: '/docs/seguranca/deteccao' },
      { title: 'Operação e conformidade', href: '/docs/seguranca/operacao' },
      { title: 'Fronteira de capacidade', href: '/docs/seguranca/capacidade' },
      { title: 'Garantias por construção', href: '/docs/seguranca' },
      { title: 'Arcane.Seguranca', href: '/docs/biblioteca/seguranca' },
      { title: 'Arcane.Politica', href: '/docs/biblioteca/politica' },
      { title: 'Arcane.Chaves', href: '/docs/biblioteca/chaves' },
      { title: 'Arcane.Deteccao', href: '/docs/biblioteca/deteccao' },
    ],
  },
  {
    title: 'Roadmap',
    standalone: true,
    items: [{ title: 'Roadmap', href: '/docs/roadmap' }],
  },
  {
    title: 'Contribuir',
    standalone: true,
    items: [{ title: 'Contribuir', href: '/docs/contribuir' }],
  },
];

/** Todas as rotas, achatadas — usado pelo "anterior/próximo" e pela busca. */
export const allRoutes: NavItem[] = nav.flatMap((s) => s.items);

/** Descobre a seção a que uma rota pertence. */
export function sectionOf(href: string): NavSection | undefined {
  return nav.find((s) => s.items.some((i) => i.href === href));
}

/** Vizinhos na ordem de leitura, para a navegação de rodapé. */
export function neighbours(href: string) {
  const i = allRoutes.findIndex((r) => r.href === href);
  return {
    prev: i > 0 ? allRoutes[i - 1] : undefined,
    next: i >= 0 && i < allRoutes.length - 1 ? allRoutes[i + 1] : undefined,
  };
}
