/**
 * Estrutura de navegação da documentação do DataForge.
 *
 * Espelha a arquitetura de informação de uma documentação de linguagem madura:
 * uma introdução, uma visão geral progressiva, fundamentos, técnicas aplicadas,
 * a biblioteca padrão, as ferramentas, os exercícios e a referência formal.
 */

export type NavItem = {
  title: string;
  href: string;
  badge?: string;
};

export type NavSection = {
  title: string;
  items: NavItem[];
  /** Seções de item único aparecem como link direto, sem acordeão. */
  standalone?: boolean;
  badge?: string;
  /** Começa aberta na primeira visita. */
};

export const nav: NavSection[] = [
  {
    title: 'Introdução',
    standalone: true,
    items: [{ title: 'Introdução', href: '/docs' }],
  },
  {
    title: 'Visão geral',
    items: [
      { title: 'Primeiros passos', href: '/docs/primeiros-passos' },
      { title: 'Olá, mundo — de verdade', href: '/docs/primeiros-passos/ola-mundo' },
      { title: 'Variáveis e contas', href: '/docs/primeiros-passos/variaveis-e-contas' },
      { title: 'Perguntar ao usuário', href: '/docs/primeiros-passos/entrada' },
      { title: 'Decidir', href: '/docs/primeiros-passos/decisoes' },
      { title: 'Repetir', href: '/docs/primeiros-passos/repeticao' },
      { title: 'Listas, vaults e conjuntos', href: '/docs/primeiros-passos/colecoes' },
      { title: 'Ações — dar nome a um pedaço de código', href: '/docs/primeiros-passos/acoes' },
      { title: 'O primeiro programa completo', href: '/docs/primeiros-passos/primeiro-programa' },
      { title: 'Ler uma mensagem de erro', href: '/docs/primeiros-passos/erros-comuns' },
      { title: 'Para onde ir agora', href: '/docs/primeiros-passos/proximos-passos' },
      { title: 'Instalação', href: '/docs/instalacao' },
      { title: 'Docker', href: '/docs/instalacao/docker' },
      { title: 'Variáveis', href: '/docs/variaveis' },
      { title: 'Tipos', href: '/docs/tipos' },
      { title: 'Operadores', href: '/docs/operadores' },
      { title: 'Condicionais', href: '/docs/condicionais' },
      { title: 'Laços', href: '/docs/lacos' },
      { title: 'Coleções', href: '/docs/colecoes' },
      { title: 'Textos', href: '/docs/textos' },
      { title: 'Ações', href: '/docs/acoes' },
      { title: 'Blueprints', href: '/docs/blueprints' },
      { title: 'Tratamento de erros', href: '/docs/erros' },
      { title: 'Pipelines', href: '/docs/pipelines' },
      { title: 'Sistema de arquivos', href: '/docs/arquivos' },
      { title: 'O REPL', href: '/docs/repl' },
    ],
  },
  {
    title: 'Fundamentos',
    items: [
      { title: 'Visão geral', href: '/docs/fundamentos' },
      { title: 'Anotações de tipo', href: '/docs/fundamentos/anotacoes-de-tipo' },
      { title: 'Records', href: '/docs/fundamentos/records' },
      { title: 'Enums', href: '/docs/fundamentos/enums' },
      { title: 'Pattern matching', href: '/docs/fundamentos/pattern-matching' },
      { title: 'Desestruturação', href: '/docs/fundamentos/desestruturacao' },
      { title: 'Spread e rest', href: '/docs/fundamentos/spread' },
      { title: 'Compreensões', href: '/docs/fundamentos/compreensoes' },
      { title: 'Interpolação', href: '/docs/fundamentos/interpolacao' },
      { title: 'Generators', href: '/docs/fundamentos/generators' },
      { title: 'Closures e lambdas', href: '/docs/fundamentos/closures' },
      { title: 'Decoradores', href: '/docs/fundamentos/decoradores' },
      { title: 'Decoradores avançados', href: '/docs/fundamentos/decoradores-avancados' },
      { title: 'Traits', href: '/docs/fundamentos/traits' },
      { title: 'Generics', href: '/docs/fundamentos/generics' },
      { title: 'Escopo', href: '/docs/fundamentos/escopo' },
      { title: 'Módulos', href: '/docs/fundamentos/modulos' },
      { title: 'Conjuntos', href: '/docs/fundamentos/conjuntos' },
      { title: 'Números', href: '/docs/fundamentos/numeros' },
      { title: 'Verdade e ausência', href: '/docs/fundamentos/ausencia' },
      { title: 'Conversões', href: '/docs/fundamentos/conversoes' },
      { title: 'Igualdade e comparação', href: '/docs/fundamentos/igualdade' },
      { title: 'Imutabilidade', href: '/docs/fundamentos/imutabilidade' },
      { title: 'Texto a fundo', href: '/docs/fundamentos/textos-avancados' },
      { title: 'Ações como valores', href: '/docs/fundamentos/ordem-superior' },
      { title: 'Recursão', href: '/docs/fundamentos/recursao' },
      // O sistema de tipos morava num grupo próprio, e isso o punha a
      // oito seções de distância de 'Anotações de tipo', que é onde
      // quem procura por ele começa. Os títulos que colidiam com um
      // item já existente aqui foram desambiguados — dois 'Generics'
      // no mesmo menu não dizem qual é qual.
      { title: 'Sistema de tipos: visão geral', href: '/docs/tipos/visao-geral' },
      { title: 'Tipos nomeados', href: '/docs/tipos-nomeados' },
      { title: 'Tuplas', href: '/docs/tipos/tuplas' },
      { title: 'Resultado e Talvez', href: '/docs/tipos/resultado' },
      { title: 'Reflexão de tipos', href: '/docs/tipos/reflexao' },
      { title: 'Fundamentos e tipos: o mapa', href: '/docs/tipos/mapa' },
      { title: 'Generics: o sistema de tipos', href: '/docs/tipos/genericos' },
      { title: 'Tipos literais', href: '/docs/tipos/literais' },
      { title: 'Métodos embutidos', href: '/docs/tipos/metodos-embutidos' },
      { title: 'Sistema de traits', href: '/docs/tipos/traits' },
    ],
  },
  {
    title: 'Módulos e empacotamento',
    items: [
      { title: 'O sistema de módulos', href: '/docs/modulos' },
      { title: 'Resolução', href: '/docs/modulos/resolucao' },
      { title: 'Carga, ordem e ciclos', href: '/docs/modulos/carga' },
      { title: 'A superfície de um módulo', href: '/docs/modulos/superficie' },
      { title: 'Templates e visão', href: '/docs/modulos/templates' },
      { title: 'As formas de adopt', href: '/docs/modulos/adopt' },
      { title: 'Relay — o que sai', href: '/docs/modulos/relay' },
      { title: 'Usar um pacote', href: '/docs/modulos/pacotes' },
      { title: 'O lockfile', href: '/docs/modulos/lockfile' },
      { title: 'O registro', href: '/docs/modulos/registro' },
      { title: 'Workspace e monorepo', href: '/docs/modulos/monorepo' },
      { title: 'Organizar um projeto grande', href: '/docs/modulos/organizar' },
      { title: 'Quando o import não resolve', href: '/docs/modulos/diagnostico' },
      { title: 'Testar código modular', href: '/docs/modulos/testar' },
      { title: 'Renomear sem quebrar', href: '/docs/modulos/renomear' },
      { title: 'A fachada: um index.df', href: '/docs/modulos/fachada' },
      { title: 'Ciclos de import', href: '/docs/modulos/ciclos' },
      { title: 'O que é público', href: '/docs/modulos/visibilidade' },
      { title: 'Achar na biblioteca padrão', href: '/docs/modulos/biblioteca-padrao' },
      { title: 'O estado de um módulo', href: '/docs/modulos/estado' },
      { title: 'O ponto de entrada', href: '/docs/modulos/entrada' },
      { title: 'Adotar do Python', href: '/docs/modulos/python' },
      { title: 'Dividir um arquivo grande', href: '/docs/modulos/dividir' },
    ],
  },
  {
    title: 'Bibliotecas',
    items: [
      { title: 'Escrever uma biblioteca', href: '/docs/bibliotecas' },
      { title: 'Estrutura', href: '/docs/bibliotecas/estrutura' },
      { title: 'O contrato', href: '/docs/bibliotecas/contrato' },
      { title: 'Testes de biblioteca', href: '/docs/bibliotecas/testes' },
      { title: 'Versão e compatibilidade', href: '/docs/bibliotecas/versao' },
      { title: 'Publicar', href: '/docs/bibliotecas/publicar' },
      { title: 'Manter', href: '/docs/bibliotecas/manutencao' },
      { title: 'Desenhar a API pública', href: '/docs/bibliotecas/api' },
      { title: 'O vault de opções', href: '/docs/bibliotecas/opcoes' },
      { title: 'Os erros da sua biblioteca', href: '/docs/bibliotecas/erros' },
      { title: 'Documentar', href: '/docs/bibliotecas/documentar' },
      { title: 'Prometer desempenho', href: '/docs/bibliotecas/desempenho' },
      { title: 'A biblioteca como superfície', href: '/docs/bibliotecas/seguranca' },
      { title: 'O CI de uma biblioteca', href: '/docs/bibliotecas/ci' },
      { title: 'Embrulhar uma do Python', href: '/docs/bibliotecas/ponte' },
      { title: 'Quatro bibliotecas de verdade', href: '/docs/bibliotecas/exemplos' },
      { title: 'Marcar o que vai sumir', href: '/docs/bibliotecas/obsolescencia' },
      { title: 'API experimental', href: '/docs/bibliotecas/experimental' },
      { title: 'O CHANGELOG', href: '/docs/bibliotecas/changelog' },
      { title: 'Licença', href: '/docs/bibliotecas/licenca' },
      { title: 'Escolher dependências', href: '/docs/bibliotecas/dependencias' },
      { title: 'Mensagens para quem não leu o código', href: '/docs/bibliotecas/mensagens' },
      { title: 'A promessa de estabilidade', href: '/docs/bibliotecas/estabilidade' },
      { title: 'Guia de migração', href: '/docs/bibliotecas/migracao' },
      { title: 'Checklist de release', href: '/docs/bibliotecas/checklist' },
    ],
  },
  {
    title: 'Orientação a objetos',
    items: [
      { title: 'Visão geral', href: '/docs/oop' },
      { title: 'Fundamentos', href: '/docs/oop/fundamentos' },
      { title: 'Blueprints', href: '/docs/oop/blueprints' },
      { title: 'Campos e visibilidade', href: '/docs/oop/campos' },
      { title: 'Propriedades', href: '/docs/oop/propriedades' },
      { title: 'Métodos estáticos', href: '/docs/oop/estaticos' },
      { title: 'Sobrecarga de operadores', href: '/docs/oop/operadores' },
      { title: 'Métodos mágicos', href: '/docs/oop/magicos' },
      { title: 'slots', href: '/docs/oop/slots' },
      { title: 'Herança e traits', href: '/docs/oop/heranca' },
      { title: 'MRO — resolução', href: '/docs/oop/mro' },
      { title: 'Abstratos e contratos', href: '/docs/oop/abstratos' },
      { title: 'Encapsulamento', href: '/docs/oop/encapsulamento' },
      { title: 'Polimorfismo', href: '/docs/oop/polimorfismo' },
      { title: 'Relacionamentos', href: '/docs/oop/relacionamentos' },
      { title: 'Modificadores', href: '/docs/oop/modificadores' },
      { title: 'Contratos', href: '/docs/oop/contratos' },
      { title: 'Sobrecarga', href: '/docs/oop/sobrecarga' },
      { title: 'Metaclasses', href: '/docs/oop/metaclasses' },
      { title: 'augment', href: '/docs/oop/augment' },
      { title: 'Reflexão', href: '/docs/oop/reflexao' },
      { title: 'Cópia, imutabilidade e serialização', href: '/docs/oop/objetos' },
      { title: 'Injeção de dependência', href: '/docs/oop/injecao' },
      { title: 'Padrões de projeto', href: '/docs/oop/padroes' },
      { title: 'Ciclo de vida e memória', href: '/docs/oop/memoria' },
      { title: 'Métricas e cheiros', href: '/docs/oop/metricas' },
      { title: 'SOLID', href: '/docs/oop/solid' },
      { title: 'Modelagem', href: '/docs/oop/modelagem' },
      // Metaprogramação vinha num grupo próprio, longe de 'Metaclasses'
      // e 'Reflexão' — que são a porta de entrada dela e vivem aqui.
      { title: 'comptime', href: '/docs/metaprogramacao/comptime' },
      { title: 'Macros', href: '/docs/metaprogramacao/macros' },
      { title: 'DSLs', href: '/docs/metaprogramacao/dsl' },
      { title: 'Plugins do check', href: '/docs/metaprogramacao/plugins' },
      { title: 'Metaprogramação: o mapa', href: '/docs/metaprogramacao/mapa' },
    ],
  },
  {
    title: 'Banco de dados',
    items: [
      { title: 'Forge — visão geral', href: '/docs/banco-de-dados' },
      { title: 'Construtor de consultas', href: '/docs/banco-de-dados/consultas' },
      { title: 'Transações e pool', href: '/docs/banco-de-dados/transacoes' },
      { title: 'Cada motor', href: '/docs/banco-de-dados/motores' },
      { title: 'O banco em contêiner', href: '/docs/banco-de-dados/docker' },
      { title: 'PostgreSQL', href: '/docs/banco-de-dados/postgres' },
      { title: 'MySQL e MariaDB', href: '/docs/banco-de-dados/mysql' },
      { title: 'Redis e MongoDB', href: '/docs/banco-de-dados/chave-valor' },
      { title: 'Em produção', href: '/docs/banco-de-dados/producao' },
      { title: 'Receitas', href: '/docs/banco-de-dados/receitas' },
      { title: 'ORM', href: '/docs/orm' },
      { title: 'Relações', href: '/docs/orm/relacoes' },
      { title: 'Migrações', href: '/docs/orm/migracoes' },
      { title: 'Carga antecipada', href: '/docs/orm/atraves' },
      { title: 'Escopos e paginação', href: '/docs/orm/escopos' },
      { title: 'Validação e ganchos', href: '/docs/orm/validacao' },
    ],
  },
  {
    title: 'Dados, ETL e SQLite',
    items: [
      { title: 'Análise de dados', href: '/docs/dados' },
      { title: 'Quadro — a tabela', href: '/docs/dados/quadro' },
      { title: 'Os verbos do pipeline', href: '/docs/dados/verbos' },
      { title: 'ETL', href: '/docs/dados/etl' },
      { title: 'Qualidade de dados', href: '/docs/dados/qualidade' },
      { title: 'SQLite', href: '/docs/sqlite' },
      { title: 'O mapa do ecossistema', href: '/docs/dados/mapa' },
      { title: 'Janelas', href: '/docs/dados/janelas' },
      { title: 'Séries temporais', href: '/docs/dados/series-temporais' },
      { title: 'Juntar quadros', href: '/docs/dados/juntar' },
      { title: 'Pivotar e despivotar', href: '/docs/dados/pivotar' },
      { title: 'Limpar dados', href: '/docs/dados/limpeza' },
      { title: 'Estatística descritiva', href: '/docs/dados/estatistica' },
      { title: 'Amostrar', href: '/docs/dados/amostragem' },
      { title: 'Exportar', href: '/docs/dados/exportar' },
      { title: 'Muitos dados', href: '/docs/dados/volume' },
      { title: 'Engenharia de dados', href: '/docs/dados/engenharia' },
      { title: 'Janelas por grupo', href: '/docs/dados/particao' },
      { title: 'Junções que não inflam', href: '/docs/dados/cardinalidade' },
      { title: 'Deriva de esquema', href: '/docs/dados/deriva' },
      { title: 'Carga incremental', href: '/docs/dados/incremental' },
      { title: 'Contratos de dados', href: '/docs/dados/contratos' },
      { title: 'Observar um pipeline', href: '/docs/dados/observar-pipeline' },
      { title: 'Do quadro ao gráfico', href: '/docs/dados/visualizar' },
      { title: 'Data Lake', href: '/docs/tecnicas/lago' },
      { title: 'Parquet', href: '/docs/tecnicas/parquet' },
      { title: 'Aprendizado de máquina', href: '/docs/tecnicas/ml' },
    ],
  },
  {
    title: 'Crucible — testes',
    items: [
      { title: 'Testes: visão geral', href: '/docs/testes' },
      { title: 'TDD', href: '/docs/testes/tdd' },
      { title: 'Testes unitários', href: '/docs/testes/unitarios' },
      { title: 'Parametrizados', href: '/docs/testes/parametrizados' },
      { title: 'Cenários (BDD)', href: '/docs/testes/bdd' },
      { title: 'Integração', href: '/docs/testes/integracao' },
      { title: 'Ponta a ponta', href: '/docs/testes/ponta-a-ponta' },
      { title: 'Testar erros', href: '/docs/testes/erros' },
      { title: 'Regressão', href: '/docs/testes/regressao' },
      { title: 'A pirâmide', href: '/docs/testes/piramide' },
      { title: 'Testes instáveis', href: '/docs/testes/instaveis' },
      { title: 'Crucible', href: '/docs/crucible' },
      { title: 'Os matchers', href: '/docs/crucible/matchers' },
      { title: 'Fixtures e ganchos', href: '/docs/crucible/fixtures' },
      { title: 'Dublês', href: '/docs/crucible/dubles' },
      { title: 'Teste por propriedade', href: '/docs/crucible/propriedades' },
      { title: 'Relatórios e CI', href: '/docs/crucible/relatorios' },
      { title: 'Cenários', href: '/docs/crucible/cenarios' },
      { title: 'Contratos e mutação', href: '/docs/crucible/mutacao' },
    ],
  },
  {
    title: 'Complexidade',
    items: [
      { title: 'Big-O', href: '/docs/big-o' },
      { title: 'As classes', href: '/docs/big-o/classes' },
      { title: 'Analisar o seu código', href: '/docs/big-o/analisar' },
      { title: 'Padrões e como melhorar', href: '/docs/big-o/padroes' },
      { title: 'Custo das estruturas', href: '/docs/big-o/estruturas' },
      { title: 'Melhor, médio e pior', href: '/docs/big-o/casos' },
      { title: 'Complexidade de espaço', href: '/docs/big-o/espaco' },
      { title: 'Recorrências e Teorema Mestre', href: '/docs/big-o/recorrencias' },
      { title: 'Análise amortizada', href: '/docs/big-o/amortizada' },
      { title: 'Ω, Θ e limites inferiores', href: '/docs/big-o/limites' },
      { title: 'Estruturas avançadas', href: '/docs/big-o/estruturas-avancadas' },
      { title: 'Complexidade em paralelo', href: '/docs/big-o/paralelo' },
      { title: 'A constante que decide', href: '/docs/big-o/constantes' },
      { title: 'Complexidade em dados e I/O', href: '/docs/big-o/dados' },
      { title: 'Os clássicos, prontos', href: '/docs/big-o/algoritmos' },
      { title: 'Busca', href: '/docs/big-o/busca' },
      { title: 'Ordenação', href: '/docs/big-o/ordenacao' },
      { title: 'Grafos', href: '/docs/big-o/grafos' },
      { title: 'Programação dinâmica', href: '/docs/big-o/programacao-dinamica' },
      { title: 'Texto e números', href: '/docs/big-o/texto' },
      { title: 'Escolher a estrutura', href: '/docs/big-o/escolher' },
      { title: 'Medir a curva', href: '/docs/big-o/medir' },
      { title: 'Exercícios de complexidade', href: '/docs/big-o/exercicios' },
    ],
  },
  {
    title: 'Kiln — framework web',
    items: [
      { title: 'APIs: REST e RESTful', href: '/docs/api' },
      { title: 'Erros que um programa lê', href: '/docs/api/problemas' },
      { title: 'Negociação de conteúdo', href: '/docs/api/negociacao' },
      { title: 'Edição concorrente: ETag e If-Match', href: '/docs/api/precondicoes' },
      { title: 'Paginação: página, cursor e Link', href: '/docs/api/paginacao' },
      { title: 'Versionar uma API', href: '/docs/api/versionamento' },
      { title: 'Idempotência', href: '/docs/api/idempotencia' },
      { title: 'Autenticação numa API', href: '/docs/api/autenticacao' },
      { title: 'Limite de taxa', href: '/docs/api/limites' },
      { title: 'O contrato: OpenAPI', href: '/docs/api/contrato' },
      { title: 'Checklist de uma API', href: '/docs/api/checklist' },
      { title: 'Visão geral', href: '/docs/kiln' },
      { title: 'Rotas e parâmetros', href: '/docs/kiln/rotas' },
      { title: 'Respostas', href: '/docs/kiln/respostas' },
      { title: 'Páginas HTML', href: '/docs/kiln/paginas' },
      { title: 'Middleware', href: '/docs/kiln/middleware' },
      { title: 'Sessão e cookies', href: '/docs/kiln/sessao' },
      { title: 'Arquivos estáticos', href: '/docs/kiln/estaticos' },
      { title: 'Receber arquivos', href: '/docs/kiln/uploads' },
      { title: 'Tempo real', href: '/docs/kiln/tempo-real' },
      { title: 'Levar para produção', href: '/docs/kiln/producao' },
      { title: 'Referência', href: '/docs/kiln/referencia' },
    ],
  },
  {
    title: 'Telegram — bots',
    items: [
      { title: 'Visão geral', href: '/docs/telegram' },
      { title: 'Comandos e roteamento', href: '/docs/telegram/comandos' },
      { title: 'Teclados e formatação', href: '/docs/telegram/teclados' },
      { title: 'Conversas e estado', href: '/docs/telegram/conversas' },
      { title: 'Mídia, arquivos e grupos', href: '/docs/telegram/midia' },
      { title: 'Testar sem rede', href: '/docs/telegram/testes' },
      { title: 'Publicar o bot', href: '/docs/telegram/publicar' },
      { title: 'Mensagens longas', href: '/docs/telegram/mensagens-longas' },
      { title: 'Listas com páginas', href: '/docs/telegram/paginacao' },
      { title: 'Ritmo e limites do Telegram', href: '/docs/telegram/ritmo' },
      { title: 'Quem pode usar o quê', href: '/docs/telegram/permissoes' },
      { title: 'Quando o tratador falha', href: '/docs/telegram/erros' },
      { title: 'Um bot que cresce', href: '/docs/telegram/arquitetura' },
      { title: 'Receitas de bot', href: '/docs/telegram/receitas' },
      { title: 'Os limites da Bot API', href: '/docs/telegram/limites' },
    ],
  },
  {
    title: 'Domínio e DDD',
    items: [
      { title: 'Visão geral', href: '/docs/dominio' },
      { title: 'Valores e entidades', href: '/docs/dominio/valores' },
      { title: 'Agregados e invariantes', href: '/docs/dominio/agregados' },
      { title: 'Eventos e unidade de trabalho', href: '/docs/dominio/eventos' },
      { title: 'Regras e contextos', href: '/docs/dominio/contextos' },
      { title: 'Fonte de eventos', href: '/docs/dominio/fonte-de-eventos' },
      { title: 'Concorrência otimista', href: '/docs/dominio/concorrencia-otimista' },
      { title: 'Projeções', href: '/docs/dominio/projecoes' },
      { title: 'CQRS', href: '/docs/dominio/cqrs' },
      { title: 'Processos e sagas', href: '/docs/dominio/processos' },
      { title: 'Serviços de domínio', href: '/docs/dominio/servicos' },
      { title: 'Camada anticorrupção', href: '/docs/dominio/anticorrupcao' },
      { title: 'Testar o domínio', href: '/docs/dominio/testes' },
      { title: 'Modelar o domínio', href: '/docs/dominio/modelagem' },
    ],
  },
  {
    title: 'Estruturas e ponteiros',
    items: [
      { title: 'Visão geral', href: '/docs/estruturas' },
      { title: 'Blocos e janelas', href: '/docs/estruturas/janelas' },
      { title: 'Ponteiros', href: '/docs/estruturas/ponteiros' },
      { title: 'Os tipos de um campo', href: '/docs/estruturas/tipos' },
      { title: 'Alinhamento e enchimento', href: '/docs/estruturas/alinhamento' },
      { title: 'A ordem dos bytes', href: '/docs/estruturas/ordem-dos-bytes' },
      { title: 'Texto de tamanho fixo', href: '/docs/estruturas/textos' },
      { title: 'Campos de bits', href: '/docs/estruturas/bits' },
      { title: 'Operações de bits', href: '/docs/estruturas/operacoes-de-bits' },
      { title: 'Varint e zigzag', href: '/docs/estruturas/varint' },
      { title: 'Ler um PNG de verdade', href: '/docs/estruturas/png' },
      { title: 'Escrever um WAV', href: '/docs/estruturas/wav' },
      { title: 'Um protocolo binário', href: '/docs/estruturas/protocolo' },
      { title: 'Arquivo mapeado em memória', href: '/docs/estruturas/arquivo-mapeado' },
      { title: 'CRC e soma de conferência', href: '/docs/estruturas/conferencia' },
      { title: 'Ler entrada hostil', href: '/docs/estruturas/entrada-hostil' },
      { title: 'De uma struct do C para um molde', href: '/docs/estruturas/de-c-para-dataforge' },
      { title: 'Receitas binárias', href: '/docs/estruturas/receitas' },
    ],
  },
  {
    title: 'Aplicações de mesa',
    items: [
      { title: 'Bigorna: visão geral', href: '/docs/desktop' },
      { title: 'Telas, menus e atalhos', href: '/docs/desktop/telas-e-menus' },
      { title: 'Diálogos', href: '/docs/desktop/dialogos' },
      { title: 'Preferências e tema', href: '/docs/desktop/preferencias-e-tema' },
      { title: 'Os componentes', href: '/docs/desktop/componentes' },
      { title: 'Testar sem display', href: '/docs/desktop/testar' },
      { title: 'Empacotar', href: '/docs/desktop/empacotar' },
      { title: 'Uma aplicação inteira', href: '/docs/desktop/completo' },
    ],
  },
  {
    title: 'Aplicativos móveis',
    items: [
      { title: 'Brasa: visão geral', href: '/docs/mobile' },
      { title: 'Telas e navegação', href: '/docs/mobile/telas-e-navegacao' },
      { title: 'Componentes', href: '/docs/mobile/componentes' },
      { title: 'O aparelho', href: '/docs/mobile/aparelho' },
      { title: 'Testar', href: '/docs/mobile/testar' },
      { title: 'PWA e publicação', href: '/docs/mobile/pwa' },
      { title: 'Limites', href: '/docs/mobile/limites' },
      { title: 'Uma regra, três plataformas', href: '/docs/multiplataforma' },
    ],
  },
  {
    title: 'IoT e Arduino',
    items: [
      { title: 'Visão geral', href: '/docs/iot' },
      { title: 'Primeiros passos com a placa', href: '/docs/iot/primeiros-passos' },
      { title: 'As placas', href: '/docs/iot/placas' },
      { title: 'Firmata: a placa como periférico', href: '/docs/iot/firmata' },
      { title: 'Sensores: do número cru ao valor', href: '/docs/iot/sensores' },
      { title: 'Atuadores: LED, PWM, servo e relé', href: '/docs/iot/atuadores' },
      { title: 'I²C: dois fios, muitos sensores', href: '/docs/iot/i2c' },
      { title: 'Sketches: C++ gerado e gravado', href: '/docs/iot/sketches' },
      { title: 'MQTT: a placa e o resto do mundo', href: '/docs/iot/mqtt' },
      { title: 'A porta serial, crua', href: '/docs/iot/serial' },
      { title: 'Testar IoT sem placa', href: '/docs/iot/sem-placa' },
      { title: 'Firmata ou sketch: a conta', href: '/docs/iot/quando-usar' },
      { title: 'Um painel para a placa', href: '/docs/iot/painel' },
      { title: 'Telemetria: guardar o que o sensor leu', href: '/docs/iot/telemetria' },
      { title: 'Projeto: a estufa', href: '/docs/iot/projeto-estufa' },
      { title: 'Receitas de IoT', href: '/docs/iot/receitas' },
      { title: 'Quando não funciona', href: '/docs/iot/solucao-de-problemas' },
    ],
  },
  {
    title: 'Reativo',
    items: [
      { title: 'Visão geral', href: '/docs/reativo' },
      { title: 'Sinais e derivados', href: '/docs/reativo/sinais' },
      { title: 'Efeitos e propagação', href: '/docs/reativo/efeitos' },
      { title: 'Observáveis', href: '/docs/reativo/observaveis' },
      { title: 'Desfazer e refazer', href: '/docs/reativo/historico' },
      { title: 'Dados que chegam depois', href: '/docs/reativo/recursos' },
      { title: 'Operadores de fluxo', href: '/docs/reativo/operadores' },
      { title: 'Escrever em lote', href: '/docs/reativo/lote' },
      { title: 'Um formulário reativo', href: '/docs/reativo/formularios' },
      { title: 'Parar o que não se usa', href: '/docs/reativo/vazamentos' },
      { title: 'Testar código reativo', href: '/docs/reativo/testes' },
      { title: 'O estado de uma aplicação', href: '/docs/reativo/estado-da-aplicacao' },
    ],
  },
  {
    title: 'Vitrine — dashboards',
    items: [
      { title: 'Visão geral', href: '/docs/vitrine' },
      { title: 'Componentes', href: '/docs/vitrine/componentes' },
      { title: 'Painel profissional', href: '/docs/vitrine/painel' },
      { title: 'Layout', href: '/docs/vitrine/layout' },
      { title: 'Estado e cache', href: '/docs/vitrine/estado' },
      { title: 'Gráficos', href: '/docs/vitrine/graficos' },
      { title: 'Páginas e segurança', href: '/docs/vitrine/paginas' },
      { title: 'Acessibilidade e idioma', href: '/docs/vitrine/acessibilidade' },
      { title: 'Testar sem navegador', href: '/docs/vitrine/testes' },
      { title: 'Produção', href: '/docs/vitrine/producao' },
      { title: 'Um projeto completo', href: '/docs/vitrine/projeto' },
      { title: 'Referência', href: '/docs/vitrine/referencia' },
    ],
  },
  {
    title: 'FFI e nativo',
    items: [
      { title: 'Visão geral', href: '/docs/ffi' },
      { title: 'Chamar C', href: '/docs/ffi/c' },
      { title: 'Ponteiros e memória crua', href: '/docs/ffi/ponteiros' },
      { title: 'Callbacks', href: '/docs/ffi/callbacks' },
      { title: 'Os tipos do C', href: '/docs/ffi/tipos' },
      { title: 'Textos e char*', href: '/docs/ffi/textos' },
      { title: 'Erros e errno', href: '/docs/ffi/erros' },
      { title: 'Achar a biblioteca', href: '/docs/ffi/bibliotecas' },
      { title: 'Segurança na fronteira', href: '/docs/ffi/seguranca' },
      { title: 'O custo de uma chamada', href: '/docs/ffi/desempenho' },
      { title: 'FFI: o mapa', href: '/docs/ffi/mapa' },
    ],
  },
  {
    title: 'Dentro do compilador',
    items: [
      { title: 'Visão geral', href: '/docs/compilador' },
      { title: 'O caminho de compilação', href: '/docs/compilador/pipeline' },
      { title: 'HIR — a árvore sem açúcar', href: '/docs/compilador/hir' },
      { title: 'MIR — o grafo de fluxo', href: '/docs/compilador/mir' },
      { title: 'O que o fluxo prova', href: '/docs/compilador/analises' },
      { title: 'SSA e o nó φ', href: '/docs/compilador/ssa' },
      { title: 'Otimização, medida', href: '/docs/compilador/otimizacao' },
      { title: 'O backend, e o que não é', href: '/docs/compilador/backend' },
      { title: 'O lexer', href: '/docs/compilador/lexer' },
      { title: 'O parser', href: '/docs/compilador/parser' },
      { title: 'O analisador estático', href: '/docs/compilador/analisador' },
      { title: 'Dominância', href: '/docs/compilador/dominancia' },
      { title: 'Desenhar o grafo', href: '/docs/compilador/visualizar' },
      { title: 'Variáveis vivas', href: '/docs/compilador/vivas' },
      { title: 'Chamada de cauda', href: '/docs/compilador/cauda' },
      { title: 'O cache de árvores', href: '/docs/compilador/cache' },
      { title: 'O compilador: o mapa', href: '/docs/compilador/mapa' },
      { title: 'Backend: o mapa', href: '/docs/compilador/mapa-backend' },
    ],
  },
  {
    title: 'Runtime e laço de eventos',
    items: [
      { title: 'Visão geral', href: '/docs/runtime' },
      { title: 'O laço de eventos', href: '/docs/runtime/laco' },
      { title: 'O escalonador', href: '/docs/runtime/escalonador' },
      { title: 'Fibras', href: '/docs/runtime/fibras' },
      { title: 'Canais entre fibras', href: '/docs/runtime/canais' },
      { title: 'Prazos e relógios', href: '/docs/runtime/prazos' },
      { title: 'O executor', href: '/docs/runtime/executor' },
      { title: 'Contrapressão', href: '/docs/runtime/contrapressao' },
      { title: 'Quando algo falha no laço', href: '/docs/runtime/falhas' },
      { title: 'Laço, thread, async ou processo', href: '/docs/runtime/escolher' },
      { title: 'O runtime: o mapa', href: '/docs/runtime/mapa' },
    ],
  },
  {
    title: 'Observabilidade e memória',
    items: [
      { title: 'Visão geral', href: '/docs/observabilidade' },
      { title: 'Percentis, e a cauda', href: '/docs/observabilidade/perfil' },
      { title: 'A diferença é real?', href: '/docs/observabilidade/comparar' },
      { title: 'Flame graph e pausas', href: '/docs/observabilidade/chamadas' },
      { title: 'Métricas', href: '/docs/observabilidade/metricas' },
      { title: 'Rastreamento', href: '/docs/observabilidade/rastreamento' },
      { title: 'Logs estruturados', href: '/docs/observabilidade/logs' },
      { title: 'Linhagem de dados', href: '/docs/observabilidade/linhagem' },
      { title: 'SLO e orçamento de erro', href: '/docs/observabilidade/slo' },
      { title: 'Alertas que param de tocar', href: '/docs/observabilidade/alertas' },
      { title: 'Memória', href: '/docs/memoria' },
      { title: 'O coletor sob controle', href: '/docs/memoria/coletor' },
      { title: 'Observabilidade: o mapa', href: '/docs/observabilidade/mapa' },
    ],
  },
  {
    title: 'Partida e segurança',
    items: [
      { title: 'Visão geral', href: '/docs/partida' },
      { title: 'Antes da primeira linha', href: '/docs/partida/inicio' },
      { title: 'Uma variável por thread', href: '/docs/partida/por-thread' },
      { title: 'A pilha', href: '/docs/partida/pilha' },
      { title: 'Encerrar em ordem', href: '/docs/partida/encerrar' },
      { title: 'Código de saída', href: '/docs/partida/codigos-de-saida' },
      { title: 'Argumentos da linha de comando', href: '/docs/partida/argumentos' },
      { title: 'Ambiente e configuração', href: '/docs/partida/ambiente' },
      { title: 'Dentro de um contêiner', href: '/docs/partida/conteineres' },
      { title: 'Fronteira de capacidade', href: '/docs/seguranca/capacidade' },
      { title: 'Partida e segurança: o mapa', href: '/docs/partida/mapa' },
      { title: 'Hardware', href: '/docs/hardware' },
      { title: 'Hardware: o mapa', href: '/docs/hardware/mapa' },
    ],
  },
  {
    title: 'Superfície e alvos',
    items: [
      { title: 'Visão geral', href: '/docs/abi' },
      { title: 'A superfície é o contrato', href: '/docs/abi/superficie' },
      { title: 'O que quebra', href: '/docs/abi/compatibilidade' },
      { title: 'O mapa de símbolos', href: '/docs/abi/simbolos' },
      { title: 'A próxima versão, calculada', href: '/docs/abi/versao' },
      { title: 'O changelog que a superfície escreve', href: '/docs/abi/changelog' },
      { title: 'Aposentar sem quebrar', href: '/docs/abi/aposentar' },
      { title: 'O contrato no CI', href: '/docs/abi/ci' },
      { title: 'Antes do 1.0', href: '/docs/abi/zero-x' },
      { title: 'Alvos', href: '/docs/alvos' },
      { title: 'Onde este programa roda', href: '/docs/alvos/portabilidade' },
      { title: 'WebAssembly, com precisão', href: '/docs/alvos/wasm' },
      { title: 'ABI e alvos: o mapa', href: '/docs/abi/mapa' },
    ],
  },
  {
    title: 'Ecossistema e design',
    items: [
      { title: 'Visão geral', href: '/docs/ecossistema' },
      { title: 'O ecossistema, conferido', href: '/docs/ecossistema/componentes' },
      { title: 'O que não existe', href: '/docs/ecossistema/ausencias' },
      { title: 'Os dez princípios', href: '/docs/ecossistema/principios' },
      { title: 'As tensões', href: '/docs/ecossistema/tensoes' },
      { title: 'Onde o tempo vai', href: '/docs/ecossistema/percurso' },
      { title: 'Referência rápida', href: '/docs/ecossistema/referencia' },
      { title: 'Glossário', href: '/docs/ecossistema/glossario' },
      { title: 'Comparada com outras linguagens', href: '/docs/ecossistema/comparacao' },
      { title: 'A arquitetura em arquivos', href: '/docs/ecossistema/arquitetura' },
      { title: 'Decisões de desenho', href: '/docs/ecossistema/decisoes' },
      { title: 'Os números', href: '/docs/ecossistema/numeros' },
      { title: 'Ecossistema: o mapa', href: '/docs/ecossistema/mapa' },
    ],
  },
  {
    title: 'Concorrência avançada',
    items: [
      { title: 'Visão geral', href: '/docs/concorrencia' },
      { title: 'Memória transacional', href: '/docs/concorrencia/stm' },
      { title: 'Atômicos e sem trava', href: '/docs/concorrencia/sem-trava' },
      { title: 'Atores', href: '/docs/concorrencia/atores' },
      { title: 'Canais entre threads', href: '/docs/concorrencia/canais' },
      { title: 'Travas', href: '/docs/concorrencia/travas' },
      { title: 'Condição de corrida', href: '/docs/concorrencia/corridas' },
      { title: 'Impasse', href: '/docs/concorrencia/impasse' },
      { title: 'Processos', href: '/docs/concorrencia/processos' },
      { title: 'Padrões de concorrência', href: '/docs/concorrencia/padroes' },
      { title: 'Contrapressão', href: '/docs/concorrencia/contrapressao' },
      { title: 'Prazo e cancelamento', href: '/docs/concorrencia/prazo' },
      { title: 'Paralelismo de dados', href: '/docs/concorrencia/dados' },
      { title: 'O que dá para compartilhar', href: '/docs/concorrencia/biblioteca' },
      { title: 'Medir sem inventar ganho', href: '/docs/concorrencia/medir' },
      { title: 'Depurar uma corrida', href: '/docs/concorrencia/depurar' },
      { title: 'Concorrência: o mapa', href: '/docs/concorrencia/mapa' },
    ],
  },
  {
    title: 'Memória e recursos',
    items: [
      { title: 'Posse e empréstimo', href: '/docs/memoria/posse' },
      { title: 'O arquivo, o soquete e a conexão', href: '/docs/memoria/posse/recursos' },
      { title: 'Mover, emprestar e copiar', href: '/docs/memoria/posse/mover' },
      { title: 'Compartilhado e referência fraca', href: '/docs/memoria/posse/compartilhado' },
      { title: 'O que o check prova', href: '/docs/memoria/posse/analise' },
      { title: 'Um pool de recursos', href: '/docs/memoria/posse/pool' },
      { title: 'De Rust e de C++ para cá', href: '/docs/memoria/posse/de-rust-e-cpp' },
      { title: 'Escopo de recursos', href: '/docs/memoria/escopo' },
      { title: 'Memória e layout', href: '/docs/memoria/layout' },
      { title: 'Memória determinística: o mapa', href: '/docs/memoria/mapa' },
    ],
  },
  {
    title: 'Lavra — consulta',
    items: [
      { title: 'Visão geral', href: '/docs/lavra' },
      { title: 'O esquema', href: '/docs/lavra/esquema' },
      { title: 'A consulta', href: '/docs/lavra/consulta' },
      { title: 'Resolvedores', href: '/docs/lavra/resolvedores' },
      { title: 'Desempenho', href: '/docs/lavra/desempenho' },
      { title: 'Segurança', href: '/docs/lavra/seguranca' },
      { title: 'O servidor', href: '/docs/lavra/servidor' },
      { title: 'Federação', href: '/docs/lavra/federacao' },
      { title: 'Mudanças', href: '/docs/lavra/mutacoes' },
      { title: 'Paginação por cursor', href: '/docs/lavra/paginacao' },
      { title: 'N+1 e o lote', href: '/docs/lavra/lote' },
      { title: 'Escalares próprios', href: '/docs/lavra/escalares' },
      { title: 'Testar um esquema', href: '/docs/lavra/testar' },
      { title: 'Do REST para o Lavra', href: '/docs/lavra/do-rest' },
      { title: 'Na prática', href: '/docs/lavra/pratica' },
    ],
  },
  {
    title: 'Técnicas',
    items: [
      { title: 'Análise estática', href: '/docs/tecnicas/analise-estatica' },
      { title: 'Testes', href: '/docs/tecnicas/testes' },
      { title: 'Cobertura', href: '/docs/tecnicas/cobertura' },
      { title: 'Instantâneos e isolamento', href: '/docs/tecnicas/instantaneos' },
      { title: 'Formatação', href: '/docs/tecnicas/formatacao' },
      { title: 'Lint', href: '/docs/tecnicas/lint' },
      { title: 'Documentação', href: '/docs/tecnicas/documentacao' },
      { title: 'Estrutura de projeto', href: '/docs/tecnicas/projeto' },
      { title: 'Concorrência', href: '/docs/tecnicas/concorrencia' },
      { title: 'Benchmark', href: '/docs/tecnicas/bench' },
      { title: 'Streams', href: '/docs/tecnicas/streams' },
      { title: 'Serialização', href: '/docs/tecnicas/serializacao' },
      { title: 'Arquivos', href: '/docs/tecnicas/arquivos' },
      { title: 'Banco de dados', href: '/docs/tecnicas/banco-de-dados' },
      { title: 'CRUD completo', href: '/docs/tecnicas/banco-de-dados/crud' },
      { title: 'Relatórios e busca', href: '/docs/tecnicas/banco-de-dados/relatorios' },
      { title: 'Migrações', href: '/docs/tecnicas/banco-de-dados/migracoes' },
      { title: 'Pipelines e orquestração', href: '/docs/tecnicas/pipeline' },
      { title: 'Qualidade de dados', href: '/docs/tecnicas/qualidade' },
      { title: 'Parquet', href: '/docs/tecnicas/parquet' },
      { title: 'Data Lake', href: '/docs/tecnicas/lago' },
      { title: 'Aprendizado de máquina', href: '/docs/tecnicas/ml' },
      { title: 'Streaming', href: '/docs/tecnicas/streaming' },
      { title: 'Observabilidade e linhagem', href: '/docs/tecnicas/observar' },
      { title: 'Planilhas', href: '/docs/tecnicas/planilhas' },
      { title: 'Microserviços', href: '/docs/tecnicas/microservicos' },
      { title: 'OpenAPI, Insomnia e Postman', href: '/docs/tecnicas/api' },
      { title: 'Servidor HTTP', href: '/docs/tecnicas/http' },
      { title: 'Editor e extensão', href: '/docs/editor' },
      { title: 'Servidor de linguagem (LSP)', href: '/docs/tecnicas/lsp' },
      { title: 'Logging', href: '/docs/tecnicas/logging' },
      { title: 'Datas e horas', href: '/docs/tecnicas/datas' },
      { title: 'Processos', href: '/docs/tecnicas/processos' },
      { title: 'Criptografia', href: '/docs/tecnicas/criptografia' },
      { title: 'Número exato (Decimal)', href: '/docs/tecnicas/decimal' },
      { title: 'A ponte para o Python', href: '/docs/tecnicas/ponte' },
    ],
  },
  {
    title: 'DevOps e produção',
    items: [
      { title: 'Visão geral', href: '/docs/devops' },
      { title: 'Docker e Compose', href: '/docs/devops/docker' },
      { title: 'Kubernetes', href: '/docs/devops/kubernetes' },
      { title: 'Helm e Terraform', href: '/docs/devops/helm-terraform' },
      { title: 'GitHub Actions', href: '/docs/devops/github-actions' },
      { title: 'Um passo em DataForge', href: '/docs/devops/actions-na-linguagem' },
      { title: 'Webhooks do GitHub', href: '/docs/devops/webhooks' },
      { title: 'A API do GitHub', href: '/docs/devops/api-github' },
      { title: 'Release por tag', href: '/docs/devops/release' },
      { title: 'O repositório', href: '/docs/devops/repositorio' },
      { title: 'GitLab CI', href: '/docs/devops/gitlab' },
      { title: 'Devcontainer e pre-commit', href: '/docs/devops/ambiente-de-dev' },
      { title: 'Numa VM (systemd)', href: '/docs/devops/vm' },
      { title: 'A imagem oficial', href: '/docs/instalacao/docker' },
      { title: 'Observabilidade', href: '/docs/tecnicas/observar' },
      { title: 'Segurança', href: '/docs/seguranca' },
      { title: 'Vitrine em produção', href: '/docs/vitrine/producao' },
      { title: 'Kiln em produção', href: '/docs/kiln/producao' },
    ],
  },
  {
    title: 'Biblioteca Arcane',
    items: [
      { title: 'Visão geral', href: '/docs/biblioteca' },
      { title: 'Arcane.API', href: '/docs/biblioteca/api' },
      { title: 'Arcane.Abi', href: '/docs/biblioteca/abi' },
      { title: 'Arcane.Algoritmos', href: '/docs/biblioteca/algoritmos' },
      { title: 'Arcane.Alvo', href: '/docs/biblioteca/alvo' },
      { title: 'Arcane.Analytics', href: '/docs/biblioteca/analytics' },
      { title: 'Arcane.Archive', href: '/docs/biblioteca/archive' },
      { title: 'Arcane.Async', href: '/docs/biblioteca/async' },
      { title: 'Arcane.Bench', href: '/docs/biblioteca/bench' },
      { title: 'Arcane.Bigorna', href: '/docs/biblioteca/bigorna' },
      { title: 'Arcane.Brasa', href: '/docs/biblioteca/brasa' },
      { title: 'Arcane.Bytes', href: '/docs/biblioteca/bytes' },
      { title: 'Arcane.C', href: '/docs/biblioteca/c' },
      { title: 'Arcane.Capacidade', href: '/docs/biblioteca/capacidade' },
      { title: 'Arcane.Chaves', href: '/docs/biblioteca/chaves' },
      { title: 'Arcane.Cli', href: '/docs/biblioteca/cli' },
      { title: 'Arcane.Collections', href: '/docs/biblioteca/collections' },
      { title: 'Arcane.Color', href: '/docs/biblioteca/color' },
      { title: 'Arcane.Compilador', href: '/docs/biblioteca/compilador' },
      { title: 'Arcane.Concurrent', href: '/docs/biblioteca/concurrent' },
      { title: 'Arcane.Cortex', href: '/docs/biblioteca/cortex' },
      { title: 'Arcane.Crucible', href: '/docs/biblioteca/crucible' },
      { title: 'Arcane.Crypto', href: '/docs/biblioteca/crypto' },
      { title: 'Arcane.Data', href: '/docs/biblioteca/data' },
      { title: 'Arcane.Database', href: '/docs/biblioteca/database' },
      { title: 'Arcane.Decimal', href: '/docs/biblioteca/decimal' },
      { title: 'Arcane.Deteccao', href: '/docs/biblioteca/deteccao' },
      { title: 'Arcane.Dominio', href: '/docs/biblioteca/dominio' },
      { title: 'Arcane.Dsl', href: '/docs/biblioteca/dsl' },
      { title: 'Arcane.Ecossistema', href: '/docs/biblioteca/ecossistema' },
      { title: 'Arcane.Email', href: '/docs/biblioteca/email' },
      { title: 'Arcane.Estrutura', href: '/docs/biblioteca/estrutura' },
      { title: 'Arcane.Eventos', href: '/docs/biblioteca/eventos' },
      { title: 'Arcane.Evolucao', href: '/docs/biblioteca/evolucao' },
      { title: 'Arcane.Excel', href: '/docs/biblioteca/excel' },
      { title: 'Arcane.Forge', href: '/docs/biblioteca/forge' },
      { title: 'Arcane.Functional', href: '/docs/biblioteca/functional' },
      { title: 'Arcane.GitHub', href: '/docs/biblioteca/github' },
      { title: 'Arcane.Gramatica', href: '/docs/biblioteca/gramatica' },
      { title: 'Arcane.Html', href: '/docs/biblioteca/html' },
      { title: 'Arcane.Http', href: '/docs/biblioteca/http' },
      { title: 'Arcane.IO', href: '/docs/biblioteca/io' },
      { title: 'Arcane.Inicio', href: '/docs/biblioteca/inicio' },
      { title: 'Arcane.Injecao', href: '/docs/biblioteca/injecao' },
      { title: 'Arcane.IoT', href: '/docs/biblioteca/iot' },
      { title: 'Arcane.Janela', href: '/docs/biblioteca/janela' },
      { title: 'Arcane.Iter', href: '/docs/biblioteca/iter' },
      { title: 'Arcane.Laco', href: '/docs/biblioteca/laco' },
      { title: 'Arcane.Lago', href: '/docs/biblioteca/lago' },
      { title: 'Arcane.Lavra', href: '/docs/biblioteca/lavra' },
      { title: 'Arcane.Logging', href: '/docs/biblioteca/logging' },
      { title: 'Arcane.Macro', href: '/docs/biblioteca/macro' },
      { title: 'Arcane.Malha', href: '/docs/biblioteca/malha' },
      { title: 'Arcane.Math', href: '/docs/biblioteca/math' },
      { title: 'Arcane.Memoria', href: '/docs/biblioteca/memoria' },
      { title: 'Arcane.Meta', href: '/docs/biblioteca/meta' },
      { title: 'Arcane.OS', href: '/docs/biblioteca/os' },
      { title: 'Arcane.Objetos', href: '/docs/biblioteca/objetos' },
      { title: 'Arcane.Observar', href: '/docs/biblioteca/observar' },
      { title: 'Arcane.Padroes', href: '/docs/biblioteca/padroes' },
      { title: 'Arcane.Percurso', href: '/docs/biblioteca/percurso' },
      { title: 'Arcane.Perfil', href: '/docs/biblioteca/perfil' },
      { title: 'Arcane.Pipeline', href: '/docs/biblioteca/pipeline' },
      { title: 'Arcane.Politica', href: '/docs/biblioteca/politica' },
      { title: 'Arcane.Ponte', href: '/docs/biblioteca/ponte' },
      { title: 'Arcane.Posse', href: '/docs/biblioteca/posse' },
      { title: 'Arcane.Principios', href: '/docs/biblioteca/principios' },
      { title: 'Arcane.Process', href: '/docs/biblioteca/process' },
      { title: 'Arcane.Quadro', href: '/docs/biblioteca/quadro' },
      { title: 'Arcane.Qualidade', href: '/docs/biblioteca/qualidade' },
      { title: 'Arcane.Reativo', href: '/docs/biblioteca/reativo' },
      { title: 'Arcane.Rede', href: '/docs/biblioteca/rede' },
      { title: 'Arcane.Reflexo', href: '/docs/biblioteca/reflexo' },
      { title: 'Arcane.Regex', href: '/docs/biblioteca/regex' },
      { title: 'Arcane.Resultado', href: '/docs/biblioteca/resultado' },
      { title: 'Arcane.Seguranca', href: '/docs/biblioteca/seguranca' },
      { title: 'Arcane.Serialization', href: '/docs/biblioteca/serialization' },
      { title: 'Arcane.Stm', href: '/docs/biblioteca/stm' },
      { title: 'Arcane.Stream', href: '/docs/biblioteca/stream' },
      { title: 'Arcane.Telegram', href: '/docs/biblioteca/telegram' },
      { title: 'Arcane.Test', href: '/docs/biblioteca/test' },
      { title: 'Arcane.Text', href: '/docs/biblioteca/text' },
      { title: 'Arcane.Time', href: '/docs/biblioteca/time' },
      { title: 'Arcane.Tipos', href: '/docs/biblioteca/tipos' },
      { title: 'Arcane.Url', href: '/docs/biblioteca/url' },
      { title: 'Arcane.Web', href: '/docs/biblioteca/web' },
    ],
  },
  {
    title: 'CLI',
    items: [
      { title: 'Visão geral', href: '/docs/cli' },
      { title: 'Referência completa', href: '/docs/cli/referencia' },
      { title: 'new e info', href: '/docs/cli/new' },
      { title: 'debug, dap e lsp', href: '/docs/cli/debug' },
      { title: 'Análise do código', href: '/docs/cli/analise' },
      { title: 'profile e fix', href: '/docs/cli/profile' },
      { title: 'seguranca', href: '/docs/cli/seguranca' },
      { title: 'crucible', href: '/docs/cli/crucible' },
      { title: 'tokens, ast, ir', href: '/docs/cli/internos' },
      { title: 'abi e alvo', href: '/docs/cli/abi' },
      { title: 'completar (Tab)', href: '/docs/cli/completar' },
      { title: 'Em scripts', href: '/docs/cli/scripts' },
      { title: 'dataforge run', href: '/docs/cli/run' },
      { title: 'dataforge check', href: '/docs/cli/check' },
      { title: 'dataforge test', href: '/docs/cli/test' },
      { title: 'dataforge fmt', href: '/docs/cli/fmt' },
      { title: 'dataforge lint', href: '/docs/cli/lint' },
      { title: 'dataforge doc', href: '/docs/cli/doc' },
      { title: 'dataforge init', href: '/docs/cli/init' },
      { title: 'dataforge repl', href: '/docs/cli/repl' },
      { title: 'dataforge add', href: '/docs/cli/pacotes' },
      { title: 'dataforge watch', href: '/docs/cli/watch' },
      { title: 'dataforge bench', href: '/docs/cli/bench' },
      { title: 'dataforge explain', href: '/docs/cli/explain' },
      { title: 'dataforge editor', href: '/docs/cli/editor' },
      { title: 'forge.toml', href: '/docs/cli/forge-toml' },
    ],
  },
  {
    title: 'Exercícios',
    items: [
      { title: 'Visão geral', href: '/docs/exercicios' },
      { title: 'Fundamentos', href: '/docs/exercicios/01-fundamentos' },
      { title: 'Controle de fluxo', href: '/docs/exercicios/02-controle-fluxo' },
      { title: 'Coleções', href: '/docs/exercicios/03-colecoes' },
      { title: 'Textos', href: '/docs/exercicios/04-strings' },
      { title: 'Ações', href: '/docs/exercicios/05-acoes' },
      { title: 'Blueprints', href: '/docs/exercicios/06-blueprints' },
      { title: 'Erros', href: '/docs/exercicios/07-erros' },
      { title: 'Pipelines', href: '/docs/exercicios/08-pipelines' },
      { title: 'Módulos', href: '/docs/exercicios/09-modulos' },
      { title: 'Avançado', href: '/docs/exercicios/10-avancado' },
      { title: 'Tipos e checagem', href: '/docs/exercicios/11-tipos-e-checagem' },
      { title: 'Records e enums', href: '/docs/exercicios/12-records-e-enums' },
      { title: 'Desestruturação', href: '/docs/exercicios/13-desestruturacao' },
      { title: 'Pattern matching', href: '/docs/exercicios/14-pattern-matching' },
      { title: 'Streams', href: '/docs/exercicios/15-streams-e-generators' },
      { title: 'Módulos e projetos', href: '/docs/exercicios/16-modulos-e-projetos' },
      { title: 'Tempo e sistema', href: '/docs/exercicios/17-tempo-e-sistema' },
      { title: 'Persistência', href: '/docs/exercicios/18-dados-e-persistencia' },
      { title: 'Concorrência', href: '/docs/exercicios/19-concorrencia' },
      { title: 'Projetos finais', href: '/docs/exercicios/20-projetos-finais' },
      { title: 'OOP avançado', href: '/docs/exercicios/21-oop-avancado' },
      { title: 'Web com Kiln', href: '/docs/exercicios/22-web-kiln' },
      { title: 'Dados e planilhas', href: '/docs/exercicios/23-dados-e-planilhas' },
      { title: 'Banco de dados', href: '/docs/exercicios/24-banco-de-dados' },
      { title: 'Testes com Crucible', href: '/docs/exercicios/25-testes-crucible' },
      { title: 'Complexidade', href: '/docs/exercicios/26-complexidade' },
      { title: 'Ponte para o Python', href: '/docs/exercicios/27-ponte-python' },
      { title: 'Vitrine', href: '/docs/exercicios/28-vitrine' },
      { title: 'Banco e CRUD', href: '/docs/exercicios/29-banco-e-crud' },
      { title: 'Tempo real', href: '/docs/exercicios/30-tempo-real' },
      { title: 'Qualidade', href: '/docs/exercicios/31-qualidade' },
      { title: 'Microserviços', href: '/docs/exercicios/32-microservicos' },
      { title: 'Lavra', href: '/docs/exercicios/33-lavra' },
      { title: 'Binário e rede', href: '/docs/exercicios/34-binario-e-rede' },
      { title: 'Paralelismo', href: '/docs/exercicios/35-paralelismo' },
      { title: 'Quadro e dados', href: '/docs/exercicios/36-quadro-e-dados' },
      { title: 'OOP como sistema', href: '/docs/exercicios/37-oop-sistema' },
      { title: 'Sistema de tipos', href: '/docs/exercicios/38-tipos' },
      { title: 'Concorrência avançada', href: '/docs/exercicios/39-concorrencia-avancada' },
      { title: 'Metaprogramação', href: '/docs/exercicios/40-metaprogramacao' },
      { title: 'FFI e nativo', href: '/docs/exercicios/41-ffi-nativo' },
      { title: 'Dentro do compilador', href: '/docs/exercicios/42-compilador' },
      { title: 'Backend e otimização', href: '/docs/exercicios/43-backend' },
      { title: 'Runtime e laço de eventos', href: '/docs/exercicios/44-runtime' },
      { title: 'Observabilidade e memória', href: '/docs/exercicios/45-observabilidade' },
      { title: 'Partida, pilha e capacidade', href: '/docs/exercicios/46-partida' },
      { title: 'Superfície e alvos', href: '/docs/exercicios/47-abi-e-alvos' },
      { title: 'Ecossistema e design', href: '/docs/exercicios/48-ecossistema' },
      { title: 'Decimal exato e padrões', href: '/docs/exercicios/49-decimal-e-padroes' },
      { title: 'Domínio e DDD', href: '/docs/exercicios/50-dominio' },
      { title: 'Programação reativa', href: '/docs/exercicios/51-reativo' },
      { title: 'Estruturas e ponteiros', href: '/docs/exercicios/52-estruturas' },
      { title: 'Regex avançado', href: '/docs/exercicios/53-regex-avancado' },
      { title: 'Erros e famílias', href: '/docs/exercicios/54-erros' },
      { title: 'Métodos mágicos', href: '/docs/exercicios/55-oop-magicos' },
      { title: 'Bots de Telegram', href: '/docs/exercicios/56-telegram' },
      { title: 'Vitrine — o painel', href: '/docs/exercicios/57-vitrine-painel' },
      { title: 'IoT e Arduino', href: '/docs/exercicios/58-iot' },
      { title: 'Tipos literais', href: '/docs/exercicios/59-tipos-literais' },
    ],
  },
  {
    title: 'Pacotes',
    items: [
      { title: 'Gerenciador de pacotes', href: '/docs/pacotes' },
      { title: 'Versões lado a lado', href: '/docs/cli/versoes' },
      { title: 'Workspace', href: '/docs/cli/workspace' },
      { title: 'O cache de árvores', href: '/docs/cli/cache' },
      { title: 'Importar módulos', href: '/docs/pacotes/importar' },
      { title: 'Escrever uma biblioteca', href: '/docs/pacotes/escrever' },
      { title: 'Publicar um pacote', href: '/docs/pacotes/publicar' },
      { title: 'aleatorio', href: '/docs/pacotes/aleatorio' },
      { title: 'argumentos', href: '/docs/pacotes/argumentos' },
      { title: 'cache', href: '/docs/pacotes/cache' },
      { title: 'cofre', href: '/docs/pacotes/cofre' },
      { title: 'colecao', href: '/docs/pacotes/colecao' },
      { title: 'datas', href: '/docs/pacotes/datas' },
      { title: 'documento', href: '/docs/pacotes/documento' },
      { title: 'estado', href: '/docs/pacotes/estado' },
      { title: 'estatistica', href: '/docs/pacotes/estatistica' },
      { title: 'evento', href: '/docs/pacotes/evento' },
      { title: 'grafo', href: '/docs/pacotes/grafo' },
      { title: 'medida', href: '/docs/pacotes/medida' },
      { title: 'modelo', href: '/docs/pacotes/modelo' },
      { title: 'moeda', href: '/docs/pacotes/moeda' },
      { title: 'progresso', href: '/docs/pacotes/progresso' },
      { title: 'registro', href: '/docs/pacotes/registro' },
      { title: 'tentativa', href: '/docs/pacotes/tentativa' },
      { title: 'texto', href: '/docs/pacotes/texto' },
      { title: 'validador', href: '/docs/pacotes/validador' },
      { title: 'tabela', href: '/docs/pacotes/tabela' },
    ],
  },
  {
    title: 'Projetos',
    items: [
      { title: 'Visão geral', href: '/docs/projetos' },
      { title: 'Gestor de tarefas', href: '/docs/projetos/gestor-tarefas' },
      { title: 'Análise de vendas', href: '/docs/projetos/analise-vendas' },
      { title: 'API de links', href: '/docs/projetos/api-links' },
      { title: 'CLI de anotações', href: '/docs/projetos/cli-notas' },
      { title: 'API REST com CRUD', href: '/docs/projetos/api-rest' },
      { title: 'Pipeline ETL', href: '/docs/projetos/etl' },
      { title: 'Motor de regras', href: '/docs/projetos/motor-de-regras' },
      { title: 'Jogo de terminal', href: '/docs/projetos/jogo' },
      { title: 'Cálculo financeiro', href: '/docs/projetos/folha-de-pagamento' },
      { title: 'Serviço de autenticação', href: '/docs/projetos/autenticacao' },
      { title: 'Processador de fila', href: '/docs/projetos/fila-de-trabalho' },
      { title: 'Interpretador de expressões', href: '/docs/projetos/interpretador' },
      { title: 'Fluxo de pedido', href: '/docs/projetos/maquina-de-estados' },
      { title: 'Controle de estoque', href: '/docs/projetos/estoque' },
      { title: 'Bot de atendimento', href: '/docs/projetos/bot-atendimento' },
      { title: 'Painel de dados', href: '/docs/projetos/painel' },
      { title: 'Classificador de clientes', href: '/docs/projetos/classificador' },
      { title: 'Detector em log', href: '/docs/projetos/detector-de-intrusao' },
      { title: 'Cofre de segredos', href: '/docs/projetos/cofre-de-segredos' },
      { title: 'Planilha reativa', href: '/docs/projetos/planilha-reativa' },
      { title: 'Planejador de rotas', href: '/docs/projetos/rotas' },
      { title: 'Biblioteca publicável', href: '/docs/projetos/biblioteca' },
      { title: 'Pedido distribuído', href: '/docs/projetos/saga' },
      { title: 'Agendador cron', href: '/docs/projetos/agendador' },
      { title: 'Gerador de site estático', href: '/docs/projetos/site-estatico' },
    ],
  },
  {
    title: 'Referência',
    items: [
      { title: 'Gramática (EBNF)', href: '/docs/referencia/gramatica' },
      { title: 'Gramática · Léxico', href: '/docs/referencia/gramatica/lexico' },
      { title: 'Gramática · Expressões', href: '/docs/referencia/gramatica/expressoes' },
      { title: 'Gramática · Instruções', href: '/docs/referencia/gramatica/instrucoes' },
      { title: 'Gramática · Declarações', href: '/docs/referencia/gramatica/declaracoes' },
      { title: 'Gramática · Padrões', href: '/docs/referencia/gramatica/padroes' },
      { title: 'Gramática · Módulos', href: '/docs/referencia/gramatica/modulos' },
      { title: 'Gramática · Erros e recursos', href: '/docs/referencia/gramatica/erros' },
      { title: 'Gramática · Concorrência', href: '/docs/referencia/gramatica/concorrencia' },
      { title: 'Gramática · Blocos de domínio', href: '/docs/referencia/gramatica/dominios' },
      { title: 'Gramática · Precedência, provada', href: '/docs/referencia/gramatica/precedencia' },
      { title: 'Gramática · Onde a leitura engana', href: '/docs/referencia/gramatica/ambiguidades' },
      { title: 'Gramática · A gramática, de dentro de um programa', href: '/docs/referencia/gramatica/na-linguagem' },
      { title: 'Palavras reservadas', href: '/docs/referencia/palavras-reservadas' },
      { title: 'Operadores', href: '/docs/referencia/operadores' },
      { title: 'Precedência', href: '/docs/referencia/precedencia' },
      { title: 'Sistema de tipos', href: '/docs/referencia/tipos' },
      { title: 'Hierarquia de erros', href: '/docs/referencia/erros' },
      { title: 'Funções embutidas', href: '/docs/referencia/embutidas' },
      { title: 'A máquina: como um .df executa', href: '/docs/vm' },
      { title: 'Arquitetura do runtime', href: '/docs/referencia/arquitetura' },
      { title: 'API pública (JSON)', href: '/api' },
    ],
  },
  {
    title: 'Receitas',
    items: [
      { title: 'Ferramenta de linha de comando', href: '/docs/receitas/cli' },
      { title: 'Argumentos, opções e a ajuda', href: '/docs/receitas/cli/argumentos' },
      { title: 'Subcomandos', href: '/docs/receitas/cli/subcomandos' },
      { title: 'Cor, tabela e o terminal', href: '/docs/receitas/cli/saida' },
      { title: 'Entrada: teclado, cano e arquivo', href: '/docs/receitas/cli/entrada' },
      { title: 'Configuração em camadas', href: '/docs/receitas/cli/configuracao' },
      { title: 'Código de saída, erro e Ctrl-C', href: '/docs/receitas/cli/saida-e-sinais' },
      { title: 'Testar uma ferramenta de terminal', href: '/docs/receitas/cli/testar' },
      { title: 'Completar com Tab', href: '/docs/receitas/cli/completar' },
      { title: 'Distribuir a ferramenta', href: '/docs/receitas/cli/distribuir' },
      { title: 'Uma ferramenta inteira', href: '/docs/receitas/cli/completa' },
      { title: 'API REST', href: '/docs/receitas/api-rest' },
      { title: 'Pipeline ETL', href: '/docs/receitas/etl' },
      { title: 'Análise de dados', href: '/docs/receitas/analise-de-dados' },
      { title: 'Interpretador de expressões', href: '/docs/receitas/interpretador' },
      { title: 'Validadores brasileiros', href: '/docs/receitas/validadores' },
      { title: 'Fila de trabalho', href: '/docs/receitas/fila-de-trabalho' },
      { title: 'Máquina de estados', href: '/docs/receitas/maquina-de-estados' },
      { title: 'Processamento de CSV', href: '/docs/receitas/csv' },
      { title: 'Sistema de inventário', href: '/docs/receitas/inventario' },
    ],
  },
  {
    title: 'FAQ',
    items: [
      { title: 'Perguntas frequentes', href: '/docs/faq' },
      { title: 'Erros comuns', href: '/docs/faq/erros-comuns' },
      { title: 'Idiomas', href: '/docs/idiomas' },
      { title: 'Quando NÃO usar', href: '/docs/faq/quando-nao-usar' },
      { title: 'Dá para pôr em produção?', href: '/docs/faq/producao' },
      { title: 'Desempenho', href: '/docs/faq/desempenho' },
      { title: 'Concorrência', href: '/docs/faq/concorrencia' },
      { title: 'Tipos', href: '/docs/faq/tipos' },
      { title: 'Dados e pandas', href: '/docs/faq/dados' },
      { title: 'Hardware', href: '/docs/faq/hardware' },
      { title: 'Instalação', href: '/docs/faq/instalacao' },
      { title: 'Editor', href: '/docs/faq/editor' },
      { title: 'Glossário', href: '/docs/faq/glossario' },
      { title: 'Comparação com Python', href: '/docs/faq/python' },
      { title: 'Comparação com JavaScript', href: '/docs/faq/javascript' },
      { title: 'Comparação com TypeScript', href: '/docs/faq/typescript' },
      { title: 'Migração 3.x → 4.0', href: '/docs/faq/migracao' },
    ],
  },
  {
    title: 'Versões',
    standalone: true,
    items: [{ title: 'Versões', href: '/docs/versoes' }],
  },
  {
    title: 'Segurança da informação',
    items: [
      { title: 'O mapa', href: '/docs/seguranca/mapa' },
      { title: 'Princípios', href: '/docs/seguranca/principios' },
      { title: 'Ameaças e risco', href: '/docs/seguranca/ameacas' },
      { title: 'O que a linguagem garante', href: '/docs/seguranca/linguagem' },
      { title: 'Entrada e saída', href: '/docs/seguranca/entrada' },
      { title: 'Autenticação', href: '/docs/seguranca/autenticacao' },
      { title: 'Autorização e capacidades', href: '/docs/seguranca/autorizacao' },
      { title: 'Ataques a credenciais', href: '/docs/seguranca/ataques' },
      { title: 'As ferramentas', href: '/docs/seguranca/ferramentas' },
      { title: 'Criptografia e chaves', href: '/docs/seguranca/criptografia' },
      { title: 'Detecção e resposta', href: '/docs/seguranca/deteccao' },
      { title: 'Operação e conformidade', href: '/docs/seguranca/operacao' },
      { title: 'OWASP Top 10', href: '/docs/seguranca/owasp' },
      { title: 'Segurança de API', href: '/docs/seguranca/api' },
      { title: 'Segurança na web', href: '/docs/seguranca/web' },
      { title: 'Gestão de segredos', href: '/docs/seguranca/segredos' },
      { title: 'Log seguro e auditoria', href: '/docs/seguranca/logs' },
      { title: 'LGPD na prática', href: '/docs/seguranca/privacidade' },
      { title: 'Anonimização', href: '/docs/seguranca/anonimizacao' },
      { title: 'Integridade', href: '/docs/seguranca/integridade' },
      { title: 'Cadeia de suprimentos', href: '/docs/seguranca/cadeia' },
      { title: 'Resposta a incidentes', href: '/docs/seguranca/incidentes' },
      { title: 'Fronteira de capacidade', href: '/docs/seguranca/capacidade' },
      { title: 'Garantias por construção', href: '/docs/seguranca' },
      { title: 'Arcane.Seguranca', href: '/docs/biblioteca/seguranca' },
      { title: 'Arcane.Politica', href: '/docs/biblioteca/politica' },
      { title: 'Arcane.Chaves', href: '/docs/biblioteca/chaves' },
      { title: 'Arcane.Deteccao', href: '/docs/biblioteca/deteccao' },
      { title: 'Arcane.Privacidade', href: '/docs/biblioteca/privacidade' },
      { title: 'Arcane.Integridade', href: '/docs/biblioteca/integridade' },
    ],
  },
  {
    title: 'Roadmap',
    standalone: true,
    items: [{ title: 'Roadmap', href: '/docs/roadmap' }],
  },
  {
    title: 'Contribuir',
    standalone: true,
    items: [{ title: 'Contribuir', href: '/docs/contribuir' }],
  },
];

/** Todas as rotas, achatadas — usado pelo "anterior/próximo" e pela busca. */
export const allRoutes: NavItem[] = nav.flatMap((s) => s.items);

/** Descobre a seção a que uma rota pertence. */
export function sectionOf(href: string): NavSection | undefined {
  return nav.find((s) => s.items.some((i) => i.href === href));
}

/** Vizinhos na ordem de leitura, para a navegação de rodapé. */
export function neighbours(href: string) {
  const i = allRoutes.findIndex((r) => r.href === href);
  return {
    prev: i > 0 ? allRoutes[i - 1] : undefined,
    next: i >= 0 && i < allRoutes.length - 1 ? allRoutes[i + 1] : undefined,
  };
}
