// GERADO por 'site/scripts/gerar_conteudo.py'. Nao edite aqui.
// A fonte e 'site/scripts/conteudo/exercicios.py' — mude la e rode o gerador.

import type { Metadata } from 'next';
import type { Bloco } from '@/lib/content';
import { DocPage } from '@/components/Doc';
import { Renderer } from '@/components/Renderer';

export const metadata: Metadata = {
  title: "Exercícios",
  description: "399 exercícios em 59 módulos, cada um verificando o próprio resultado.",
};

const blocos: Bloco[] = [
  {"h2": "Como funcionam"},
  {"p": "Cada exercício **verifica o próprio resultado com `assert`** — se ele roda sem erro, está correto. Não há gabarito separado: o código é a resposta e o teste ao mesmo tempo."},
  { code: `python3 exercicios/run_all.py          # todos os 399
python3 exercicios/run_all.py 14       # só o módulo 14
python3 exercicios/run_all.py 03 07    # módulos 03 e 07

dataforge run exercicios/01-fundamentos/001_ola_mundo.df`, lang: 'bash' },
  {"p": "Os módulos **11 a 59** trazem um arquivo `.md` ao lado de cada `.df`, com enunciado, conceitos, saída esperada e sugestões para experimentar."},
  {"callout": {"tipo": "nota", "titulo": "Eles rodam a cada mudança", "texto": "Os 399 são executados na suíte do repositório. Um exercício que quebrasse com uma mudança na linguagem apareceria no mesmo instante — é por isso que os exemplos desta documentação podem ser citados sem medo."}},
  {"h2": "Como praticar"},
  {"list": ["**Leia o enunciado e tente antes.** As duas primeiras linhas de cada `.df` dizem o que fazer. Escreva a sua versão num arquivo à parte e só depois compare com a resposta.", "**Rode o original.** `dataforge run exercicios/<módulo>/<arquivo>.df` termina sem erro quando está certo — não há saída \"passou\" para procurar.", "**Quebre de propósito.** Troque o valor esperado num `assert` e rode de novo: o erro aponta a linha e mostra os dois valores. É o jeito mais rápido de ler o que cada linha garante.", "**Passe o `check`.** `dataforge check` no arquivo mostra o que o analisador acusa antes de rodar. Vários exercícios provocam um erro dentro de `monitor` de propósito, e ali ele aparece como aviso.", "**Faça o \"Experimente\".** Do módulo 11 em diante, a explicação de cada exercício termina com sugestões de mudança — é onde está a parte que não se aprende só lendo."], "ordered": true},
  {"h2": "Por onde começar"},
  {"p": "Uma trilha por objetivo. Os números levam ao módulo; dentro dele, os exercícios estão em ordem de dificuldade."},
  {"table": {"head": ["Se você quer…", "Módulos, nesta ordem"], "rows": [["Aprender a linguagem do zero", "[01](/docs/exercicios/01-fundamentos) → [02](/docs/exercicios/02-controle-fluxo) → [03](/docs/exercicios/03-colecoes) → [04](/docs/exercicios/04-strings) → [05](/docs/exercicios/05-acoes) → [06](/docs/exercicios/06-blueprints) → [07](/docs/exercicios/07-erros) → [08](/docs/exercicios/08-pipelines) → [09](/docs/exercicios/09-modulos) → [10](/docs/exercicios/10-avancado)"], ["Escrever código que o `check` protege", "[11](/docs/exercicios/11-tipos-e-checagem) → [38](/docs/exercicios/38-tipos) → [59](/docs/exercicios/59-tipos-literais) → [31](/docs/exercicios/31-qualidade)"], ["Dominar pattern matching", "[12](/docs/exercicios/12-records-e-enums) → [14](/docs/exercicios/14-pattern-matching)"], ["Trabalhar com dados", "[03](/docs/exercicios/03-colecoes) → [08](/docs/exercicios/08-pipelines) → [15](/docs/exercicios/15-streams-e-generators) → [18](/docs/exercicios/18-dados-e-persistencia) → [23](/docs/exercicios/23-dados-e-planilhas) → [36](/docs/exercicios/36-quadro-e-dados) → [57](/docs/exercicios/57-vitrine-painel)"], ["Construir uma API ou um site", "[16](/docs/exercicios/16-modulos-e-projetos) → [22](/docs/exercicios/22-web-kiln) → [24](/docs/exercicios/24-banco-de-dados) → [29](/docs/exercicios/29-banco-e-crud) → [30](/docs/exercicios/30-tempo-real) → [32](/docs/exercicios/32-microservicos)"], ["Organizar um sistema grande", "[16](/docs/exercicios/16-modulos-e-projetos) → [21](/docs/exercicios/21-oop-avancado) → [37](/docs/exercicios/37-oop-sistema) → [50](/docs/exercicios/50-dominio) → [54](/docs/exercicios/54-erros)"], ["Usar mais de um núcleo", "[19](/docs/exercicios/19-concorrencia) → [35](/docs/exercicios/35-paralelismo) → [39](/docs/exercicios/39-concorrencia-avancada) → [44](/docs/exercicios/44-runtime)"], ["Escrever um bot de Telegram", "[56](/docs/exercicios/56-telegram)"], ["Ligar uma placa Arduino", "[58](/docs/exercicios/58-iot)"], ["Entender como a linguagem funciona", "[40](/docs/exercicios/40-metaprogramacao) → [42](/docs/exercicios/42-compilador) → [43](/docs/exercicios/43-backend) → [44](/docs/exercicios/44-runtime) → [48](/docs/exercicios/48-ecossistema)"]]}},
  {"h2": "Os 59 módulos, por nível"},
  {"h3": "Primeiros passos · 10 módulos, 120 exercícios"},
  {"p": "A linguagem do zero: valores, decisões, coleções, texto, ações, objetos, erros, pipelines e módulos. Faça na ordem."},
  {"table": {"head": ["Módulo", "Exercícios", "Assunto"], "rows": [["[**01 · Fundamentos**](/docs/exercicios/01-fundamentos)", "12", "tipos, operadores, precedência, conversão e anotações"], ["[**02 · Controle de fluxo**](/docs/exercicios/02-controle-fluxo)", "12", "given/orif/otherwise, ternário, match e guardas"], ["[**03 · Coleções**](/docs/exercicios/03-colecoes)", "14", "cluster e vault, fatias, spread e compreensões"], ["[**04 · Textos**](/docs/exercicios/04-strings)", "10", "interpolação, métodos de texto, formatação e regex"], ["[**05 · Ações**](/docs/exercicios/05-acoes)", "14", "parâmetros, padrões, retorno, closures e recursão"], ["[**06 · Blueprints**](/docs/exercicios/06-blueprints)", "14", "campos, métodos, herança, traits e records"], ["[**07 · Erros**](/docs/exercicios/07-erros)", "10", "monitor/handle/ensure, trigger, retry e defer"], ["[**08 · Pipelines**](/docs/exercicios/08-pipelines)", "12", "sift, morph, distill e composição"], ["[**09 · Módulos**](/docs/exercicios/09-modulos)", "12", "adopt, relay, seleção e apelidos"], ["[**10 · Avançado**](/docs/exercicios/10-avancado)", "10", "decoradores, generators, threads e canais"]]}},
  {"h3": "A linguagem a fundo · 11 módulos, 71 exercícios"},
  {"p": "O que separa um script de um programa: tipos verificados, records, padrões, streams, projetos com forge.toml, tempo, persistência, concorrência e OOP."},
  {"table": {"head": ["Módulo", "Exercícios", "Assunto"], "rows": [["[**11 · Tipos e checagem**](/docs/exercicios/11-tipos-e-checagem)", "6", "anotações, o analisador estático e generics"], ["[**12 · Records e enums**](/docs/exercicios/12-records-e-enums)", "6", "imutabilidade, 'with' e enums com valor"], ["[**13 · Desestruturação**](/docs/exercicios/13-desestruturacao)", "6", "cluster, vault, rest e troca de variáveis"], ["[**14 · Pattern matching**](/docs/exercicios/14-pattern-matching)", "6", "point, when, tipos, sequências e vaults"], ["[**15 · Streams**](/docs/exercicios/15-streams-e-generators)", "6", "stream action, emit, take e sequências infinitas"], ["[**16 · Módulos e projetos**](/docs/exercicios/16-modulos-e-projetos)", "7", "forge.toml, pacotes e organização"], ["[**17 · Tempo e sistema**](/docs/exercicios/17-tempo-e-sistema)", "6", "datas, durações, ambiente e processos"], ["[**18 · Persistência**](/docs/exercicios/18-dados-e-persistencia)", "6", "JSON, CSV, SQLite e serialização"], ["[**19 · Concorrência**](/docs/exercicios/19-concorrencia)", "6", "threads, canais, tarefas e paralelismo"], ["[**20 · Projetos finais**](/docs/exercicios/20-projetos-finais)", "6", "programas completos, de ponta a ponta"], ["[**21 · OOP avançado**](/docs/exercicios/21-oop-avancado)", "10", "propriedades, estáticos, operadores, SOLID"]]}},
  {"h3": "Aplicações · 18 módulos, 90 exercícios"},
  {"p": "Web, banco, testes, dados, tempo real, serviços, bots e hardware: cada módulo é uma peça que se usa num sistema de verdade."},
  {"table": {"head": ["Módulo", "Exercícios", "Assunto"], "rows": [["[**22 · Web com Kiln**](/docs/exercicios/22-web-kiln)", "8", "rotas, respostas, templates e estáticos"], ["[**23 · Dados e planilhas**](/docs/exercicios/23-dados-e-planilhas)", "3", "frames, agregação e .xlsx"], ["[**24 · Banco de dados**](/docs/exercicios/24-banco-de-dados)", "8", "Forge: conexão, consultas, transações e ORM"], ["[**25 · Testes com Crucible**](/docs/exercicios/25-testes-crucible)", "4", "suítes, matchers, fixtures e dublês"], ["[**26 · Complexidade**](/docs/exercicios/26-complexidade)", "4", "Big-O, memoização e custo de estrutura"], ["[**27 · Ponte para o Python**](/docs/exercicios/27-ponte-python)", "1", "adopt Python.*: numpy, pandas e o que vem junto"], ["[**28 · Vitrine**](/docs/exercicios/28-vitrine)", "1", "painéis e aplicações de dados sem escrever HTML"], ["[**29 · Banco e CRUD**](/docs/exercicios/29-banco-e-crud)", "4", "transações, upsert, busca textual e paginação"], ["[**30 · Tempo real**](/docs/exercicios/30-tempo-real)", "2", "upload, SSE e WebSocket no Kiln"], ["[**31 · Qualidade**](/docs/exercicios/31-qualidade)", "3", "check, lint, cobertura e o que o CI cobra"], ["[**32 · Microserviços**](/docs/exercicios/32-microservicos)", "2", "Arcane.Malha: retry, disjuntor, rastro e saga"], ["[**33 · Lavra**](/docs/exercicios/33-lavra)", "3", "esquema, consulta, lote contra o N+1, servidor e federação"], ["[**34 · Binário e rede**](/docs/exercicios/34-binario-e-rede)", "3", "dados binários, TCP/UDP/DNS, eventos, CLI, e-mail e HTML"], ["[**35 · Paralelismo**](/docs/exercicios/35-paralelismo)", "3", "vários núcleos de verdade, o que atravessa para outro processo"], ["[**36 · Quadro e dados**](/docs/exercicios/36-quadro-e-dados)", "1", "o quadro de dados e os seis verbos do pipeline"], ["[**56 · Bots de Telegram**](/docs/exercicios/56-telegram)", "15", "bots testados sem rede: comandos, botões, estado e webhook"], ["[**57 · Vitrine — o painel**](/docs/exercicios/57-vitrine-painel)", "15", "painéis com layout, gráficos, grade, cache e sessão"], ["[**58 · IoT e Arduino**](/docs/exercicios/58-iot)", "10", "Arduino pelo Firmata: sensores, relé, escala e sketch"]]}},
  {"h3": "Sistemas e arquitetura · 10 módulos, 108 exercícios"},
  {"p": "Para código que vai crescer: contratos e OOP como sistema, o sistema de tipos, dinheiro exato, domínio, reativo, estruturas binárias, regex, a família dos erros e os métodos mágicos."},
  {"table": {"head": ["Módulo", "Exercícios", "Assunto"], "rows": [["[**37 · OOP como sistema**](/docs/exercicios/37-oop-sistema)", "10", "contratos, modificadores, sobrecarga, metaclasse, DI e padrões"], ["[**38 · Sistema de tipos**](/docs/exercicios/38-tipos)", "5", "alias, união, refinamento, opaco, generics, tuplas e posse"], ["[**49 · Decimal exato e padrões**](/docs/exercicios/49-decimal-e-padroes)", "1", "dinheiro exato com Decimal e o padrão acusado antes de rodar"], ["[**50 · Domínio e DDD**](/docs/exercicios/50-dominio)", "15", "valor, entidade, agregado, evento, regra e unidade de trabalho"], ["[**51 · Programação reativa**](/docs/exercicios/51-reativo)", "15", "sinal, derivado, efeito, observável e o losango"], ["[**52 · Estruturas e ponteiros**](/docs/exercicios/52-estruturas)", "15", "layout binário com nome, janela sem cópia e ponteiro"], ["[**53 · Regex avançado**](/docs/exercicios/53-regex-avancado)", "15", "grupos nomeados, âncoras, troca que calcula e risco"], ["[**54 · Erros e famílias**](/docs/exercicios/54-erros)", "15", "as famílias de erro, a falha como valor e o que o monitor não pega"], ["[**55 · Métodos mágicos**](/docs/exercicios/55-oop-magicos)", "15", "métodos mágicos: texto, conta, coleção, ordem e iteração"], ["[**59 · Tipos literais**](/docs/exercicios/59-tipos-literais)", "2", "tipos literais e o método que não existe, acusado antes"]]}},
  {"h3": "Por dentro da linguagem · 10 módulos, 10 exercícios"},
  {"p": "Como a linguagem funciona por baixo: memória transacional, metaprogramação, FFI, as representações do compilador, o runtime, a medição e o contrato de uma versão."},
  {"table": {"head": ["Módulo", "Exercícios", "Assunto"], "rows": [["[**39 · Concorrência avançada**](/docs/exercicios/39-concorrencia-avancada)", "1", "memória transacional, CAS e estruturas sem trava"], ["[**40 · Metaprogramação**](/docs/exercicios/40-metaprogramacao)", "1", "comptime, macros, DSL e plugin do check"], ["[**41 · FFI e nativo**](/docs/exercicios/41-ffi-nativo)", "1", "chamar C: bibliotecas, ponteiros e callbacks"], ["[**42 · Dentro do compilador**](/docs/exercicios/42-compilador)", "1", "HIR, MIR e o que a análise de fluxo prova"], ["[**43 · Backend e otimização**](/docs/exercicios/43-backend)", "1", "SSA, o nó phi e a otimização que foi medida"], ["[**44 · Runtime e laço de eventos**](/docs/exercicios/44-runtime)", "1", "laço de eventos, escalonador e fibras"], ["[**45 · Observabilidade e memória**](/docs/exercicios/45-observabilidade)", "1", "percentis, significância e o coletor sob controle"], ["[**46 · Partida, pilha e capacidade**](/docs/exercicios/46-partida)", "1", "as fases da partida, a pilha e a fronteira de capacidade"], ["[**47 · Superfície e alvos**](/docs/exercicios/47-abi-e-alvos)", "1", "a superfície como contrato e o alvo como restrição"], ["[**48 · Ecossistema e design**](/docs/exercicios/48-ecossistema)", "1", "o mapa conferido e os princípios que se medem"]]}},
];

const headings = [{ id: 'como-funcionam', text: "Como funcionam", level: 2 as const }, { id: 'como-praticar', text: "Como praticar", level: 2 as const }, { id: 'por-onde-comecar', text: "Por onde começar", level: 2 as const }, { id: 'os-59-modulos-por-nivel', text: "Os 59 módulos, por nível", level: 2 as const }, { id: 'primeiros-passos-10-modulos-120-exercicios', text: "Primeiros passos · 10 módulos, 120 exercícios", level: 3 as const }, { id: 'a-linguagem-a-fundo-11-modulos-71-exercicios', text: "A linguagem a fundo · 11 módulos, 71 exercícios", level: 3 as const }, { id: 'aplicacoes-18-modulos-90-exercicios', text: "Aplicações · 18 módulos, 90 exercícios", level: 3 as const }, { id: 'sistemas-e-arquitetura-10-modulos-108-exercicios', text: "Sistemas e arquitetura · 10 módulos, 108 exercícios", level: 3 as const }, { id: 'por-dentro-da-linguagem-10-modulos-10-exercicios', text: "Por dentro da linguagem · 10 módulos, 10 exercícios", level: 3 as const }];

export default function Pagina() {
  return (
    <DocPage
      title={"Exercícios"}
      description={"399 exercícios em 59 módulos, cada um verificando o próprio resultado."}
      href={"/docs/exercicios"}
      headings={headings}
    >
      <Renderer blocos={blocos} />
    </DocPage>
  );
}
