// GERADO por 'site/scripts/gerar_conteudo.py'. Nao edite aqui.
// A fonte e 'site/scripts/conteudo/dados_quadro.py' — mude la e rode o gerador.

import type { Metadata } from 'next';
import type { Bloco } from '@/lib/content';
import { DocPage } from '@/components/Doc';
import { Renderer } from '@/components/Renderer';

export const metadata: Metadata = {
  title: "O mapa do ecossistema de dados",
  description: "As 32 áreas de dados, cruzadas com o que a linguagem tem: o que é nativo, o que atravessa a ponte, e o que não existe por decisão.",
};

const blocos: Bloco[] = [
  {"p": "Este documento é o **mapa**, e não a lista. Cada área do ciclo de vida do dado — ingestão, limpeza, transformação, validação, armazenamento, análise, visualização, aprendizado, governança — cruzada com o que existe, medido pelos símbolos dos módulos e não pela memória de quem escreveu."},
  {"p": "Três estados, e a diferença entre eles importa mais que a lista:"},
  {"table": {"head": ["Estado", "Significa"], "rows": [["**nativo**", "está na linguagem ou na biblioteca padrão, sem dependência nenhuma"], ["**ponte**", "existe através de `adopt Python.x` — a biblioteca é do Python, o código é seu"], ["**fora**", "não existe, e a decisão está tomada: o motivo está escrito"]]}},
  {"h2": "1 — Fundamentos e estatística descritiva"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["média, mediana, moda, variância, desvio", "**nativo** — `Quadro.descrever`, `Arcane.Analytics`"], ["mínimo, máximo, amplitude, percentis, quartis", "**nativo** — `descrever` traz q1, mediana e q3"], ["assimetria, curtose", "**nativo** — `Analytics.skewness`, `kurtosis`"], ["correlação e covariância", "**nativo** — `Quadro.correlacao`, `Analytics.covariance`"], ["outliers", "**nativo** — `Quadro.fora_da_curva` (1,5 × IQR)"], ["amostragem, amostra estratificada", "**nativo** — `Quadro.amostra`, `Analytics.stratified_sample`"], ["regressão, séries temporais", "**nativo** — `Analytics.linear_regression`, `moving_average`, `seasonality`, `trend`"], ["testes de hipótese, p-value, intervalo de confiança", "**ponte** — `adopt Python.scipy`; implementar a família inteira de testes sem dependência seria meio caminho"]]}},
  {"h2": "2 — Manipulação de dados"},
  {"p": "É a área que o [`Quadro`](/docs/dados/quadro) cobre por inteiro, e a razão de ele existir:"},
  {"table": {"head": ["O que se pede", "O verbo"], "rows": [["DataFrame, Series, indexação", "`Quadro`, `coluna`, `linha`, `q[\"col\"]`, `q[0]`, `q[0:10]`"], ["seleção de colunas e linhas, filtros, ordenação", "`pegar`, `sem`, `onde`, `ordenar`"], ["agrupamento e agregação, `group_by`", "`agrupar` + `resumir`, com 14 agregações"], ["`join`, `merge`, `concat`", "`juntar` (dentro/esquerda/direita/fora), `empilhar`"], ["pivot tables", "`pivotar`, `despivotar`, `tabela_cruzada`"], ["transformação de colunas, aplicar função", "`com`, `mapear`"], ["dados ausentes, duplicatas", "`nulos`, `sem_nulos`, `preencher`, `distintas`, `duplicadas`"], ["conversão de tipos", "`converter`, `inferir_tipos`"], ["normalização, padronização, encoding", "`normalizar`, `padronizar`, `codificar`, `discretizar`"], ["operações vetorizadas", "**parcial** — colunar por dentro; o laço ainda é do interpretador. Para vetorização de verdade, a ponte para o `numpy`"]]}},
  {"h2": "3 e 4 — ETL e ELT"},
  {"table": {"head": ["Extrair de", "Estado"], "rows": [["CSV, JSON, Excel, Parquet", "**nativo** — `Quadro.de_csv`, `de_json`, `Arcane.Excel`, `Arcane.Lago`"], ["SQLite", "**nativo** — `Arcane.Database`, 64 símbolos"], ["API REST, GraphQL", "**nativo** — `Arcane.Http`, `Arcane.Malha`, `Arcane.Lavra`"], ["arquivos locais, logs, streams", "**nativo** — `Arcane.IO`, `Arcane.Stream`"], ["XML, Avro, ORC", "**fora** — formatos de um ecossistema que a linguagem não fala; via ponte quando preciso"], ["PostgreSQL, MySQL, Oracle, MongoDB, Redis", "**ponte** — exigem driver de rede próprio, e a promessa aqui é zero dependência"], ["FTP, SFTP, Cloud Storage", "**ponte** — mesma razão"]]}},
  {"p": "Do lado da transformação, tudo é nativo: limpeza, deduplicação, normalização, conversão de tipo, tratamento de nulo, enriquecimento por `juntar`, agregação, filtro, ordenação, validação e regra de negócio — ver [ETL](/docs/dados/etl) e [qualidade](/docs/dados/qualidade)."},
  {"callout": {"tipo": "atencao", "titulo": "A parte que mais importa num ETL não é a conexão", "texto": "É a **idempotência**: rodar duas vezes tem de dar o mesmo resultado. `upsert`, `insert_or_ignore` e transação são nativos, e é deles que depende reprocessar um dia que falhou sem duplicar tudo."}},
  {"h2": "5 — Engenharia de dados"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["data pipelines, orquestração, DAG", "**nativo** — `Arcane.Pipeline`: etapa, ordem, retry, incremental, histórico"], ["batch e stream processing", "**nativo** — `parallel`, `map_processos`, `Arcane.Stream`"], ["validação e qualidade", "**nativo** — `Arcane.Qualidade`"], ["linhagem, catálogo, observabilidade", "**nativo** — `Arcane.Observar`: origem, derivar, impacto, árvore, grafo"], ["contratos de dados, evolução de esquema", "**parcial** — `Arcane.Lago.esquema` e `Arcane.Qualidade.conferir`; o registro de esquema versionado não existe"], ["event-driven pipelines", "**nativo** — `Arcane.Eventos` (em memória); a fila **com persistência** é o item aberto do roadmap"]]}},
  {"h2": "6, 7 e 19 — SQL, Data Warehouse, Data Lake e Lakehouse"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["SELECT, INSERT, UPDATE, DELETE, JOIN, índice", "**nativo** — [`Arcane.Database`](/docs/sqlite)"], ["transação, savepoint, upsert, migração", "**nativo**"], ["busca textual, `explain`, estatística de tabela", "**nativo** — FTS5, `DB.explain`, `DB.stats`"], ["ORM, modelos, relações", "**nativo** — `Arcane.Forge`"], ["Parquet, partições, camadas bronze/prata/ouro", "**nativo** — [`Arcane.Lago`](/docs/tecnicas/lago)"], ["compactação, vácuo, promoção entre camadas", "**nativo** — `Lago.compactar`, `vacuo`, `promover`"], ["modelagem dimensional, SCD, data marts", "**padrão, não módulo** — são formas de modelar, e a linguagem tem o que elas exigem (junção, upsert, versão por data)"], ["Snowflake, BigQuery, Redshift", "**fora** — são serviços; o caminho é a API deles por `Arcane.Http`"]]}},
  {"h2": "8 e 9 — Big Data e tempo real"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["processamento paralelo de verdade", "**nativo** — `P.map_processos`, medido **4,71×** em 10 núcleos"], ["processamento por partes, streaming de arquivo", "**nativo** — `stream action` + `emit`, `O(1)` de espaço"], ["particionamento, poda de partição", "**nativo** — `Arcane.Lago.particoes`"], ["filas, tópicos, offset, janelas", "**nativo** — `Arcane.Stream`: topico, publicar, consumir, offset, janela, confirmar"], ["Spark, Hadoop, Flink, Kafka", "**fora** — são sistemas distribuídos, não bibliotecas. O que a linguagem oferece é o modelo deles numa máquina"], ["dados maiores que a memória", "**parcial** — por partes, sim; o motor distribuído, não"]]}},
  {"callout": {"tipo": "nota", "titulo": "O teto, dito com número", "texto": "Uma VM de bytecode **escrita em Python** tem teto de ~6,5×. Para trabalho pesado de CPU a resposta é `map_processos` (processos de verdade) ou a ponte para o `numpy`, onde a conta acontece fora do interpretador. Isso está medido em [complexidade em paralelo](/docs/big-o/paralelo)."}},
  {"h2": "10 e 25 — Visualização e BI"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["gráfico de barras, linhas, dispersão, histograma", "**nativo** — `Arcane.Analytics` em ASCII, `Arcane.Vitrine` em SVG"], ["painel interativo, filtros, abas, métricas", "**nativo** — [Vitrine](/docs/vitrine): 40 componentes, sete gráficos, ~4 KB de cliente"], ["mapa de calor, sparkline, box plot", "**nativo** — `Analytics.heatmap`, `sparkline`, `box_plot`"], ["relatório e exportação", "**nativo** — `para_csv`, `para_json`, `Arcane.Excel`"], ["KPI, drill-down, self-service BI", "**padrão** — a Vitrine tem as peças; o produto é seu"], ["Power BI, Tableau, Looker", "**fora** — são produtos"]]}},
  {"h2": "11, 12 e 21 — Data Science, IA e séries temporais"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["regressão linear e logística, árvore, floresta", "**nativo** — `Arcane.Cortex`"], ["k-médias, k-vizinhos, PCA, Bayes", "**nativo** — `Cortex.kmedias`, `vizinhos`, `pca`, `bayes_texto`"], ["treino, teste, validação cruzada, matriz de confusão", "**nativo** — `dividir`, `validacao_cruzada`, `matriz`"], ["escalonamento, categórico, importância de feição", "**nativo** — `escalonar`, `categorico`, `importancia`"], ["média móvel, defasagem, sazonalidade, tendência", "**nativo** — `Analytics.moving_average`, `lag`, `seasonality`, `trend`"], ["rede neural, aprendizado profundo, LLM", "**ponte** — `adopt Python.torch`. Uma rede neural sem BLAS é um brinquedo, e prometê-la seria mentir"]]}},
  {"h2": "15, 23, 24, 26 e 27 — Qualidade, perfil, limpeza, observabilidade e governança"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["perfil de dados, tipos, distribuição, cardinalidade", "**nativo** — `Quadro.perfil`, `Arcane.Qualidade.perfil`"], ["completude, unicidade, validade, atualidade", "**nativo** — `Qualidade.completude`, `unicidade`, `so_validas`, `atualidade`"], ["duplicatas, valores fora da faixa, formato", "**nativo** — `duplicadas`, `fora_da_faixa`, `formatos`"], ["limpeza: nulo, tipo, texto, data", "**nativo** — `preencher`, `converter`, `Arcane.Text`, `Arcane.Time`"], ["linhagem, impacto, catálogo", "**nativo** — `Observar.origem`, `derivar`, `impacto`, `arvore`, `grafo`"], ["métricas, alerta, painel, Prometheus", "**nativo** — `Observar.medir`, `alertar`, `painel`, `prometheus`"], ["contrato de dados, política, auditoria", "**parcial** — `Qualidade.conferir` e `esperar` dão o contrato; a política e a auditoria são processo, não biblioteca"], ["mascaramento, anonimização, LGPD", "**parcial** — `Arcane.Crypto` tem o hash e a cifra; a classificação de dado pessoal é decisão de quem modela"]]}},
  {"h2": "28 e 29 — Testes e desempenho"},
  {"table": {"head": ["O que se pede", "Onde está"], "rows": [["teste unitário, de integração, de dados", "**nativo** — [Crucible](/docs/testes), com banco isolado por teste"], ["instantâneo de saída grande", "**nativo** — `expect … matches snapshot`"], ["teste por propriedade", "**nativo** — `Crucible`"], ["análise de complexidade antes de rodar", "**nativo** — `dataforge big-o`, único entre linguagens"], ["lazy evaluation, processamento por partes", "**nativo** — `stream action` + `emit`"], ["cache, memoização", "**nativo** — `Arcane.Functional.memoize`, `Vitrine.cache`"], ["armazenamento colunar", "**nativo** — o `Quadro` é colunar por dentro; o Parquet, no `Lago`"], ["predicate pushdown, otimização de consulta", "**parcial** — o SQLite otimiza a consulta; o `Quadro` não reordena o pipeline"]]}},
  {"h2": "30 — A sintaxe que o documento esboçou"},
  {"p": "O esboço propunha um operador `|>` e blocos `pipeline { }`. A linguagem já tinha o `>>`, e o que faltava era o **vocabulário** — não um segundo operador:"},
  { code: `// o esboço                          // em DataForge
// dados |> filtrar(idade > 18)       >> onde idade bigger 18
// |> agrupar.por("cidade")           >> agrupar cidade
// |> agregar.media("salario")        >> resumir {"salario": "media"}
// |> ordenar.desc("valor")           >> ordenar valor desc
`, lang: 'df' },
  { code: `resumo := vendas
    >> onde valor bigger 50
    >> agrupar produto
    >> resumir {"valor": "soma"}
    >> ordenar valor desc
`, lang: 'df' },
  {"p": "Inventar `|>` ao lado de `>>` daria dois operadores para a mesma ideia — e a primeira pergunta de quem chega seria qual usar. Os [seis verbos](/docs/dados/verbos) são **contextuais**, como as onze palavras do Kiln: valem depois de um `>>` e continuam livres como nome em todo o resto."},
  {"h2": "31 — Os módulos propostos, e onde eles foram parar"},
  {"table": {"head": ["Proposto", "Onde está"], "rows": [["`DataFrame`", "**`Arcane.Quadro`**"], ["`Data`, `Statistics`", "`Arcane.Analytics`, `Arcane.Data`"], ["`ETL`, `ELT`, `Pipelines`", "`Arcane.Pipeline` + os verbos do quadro"], ["`SQL`, `Warehouse`", "`Arcane.Database`, `Arcane.Forge`"], ["`Lake`, `Lakehouse`", "`Arcane.Lago`"], ["`Streaming`, `BigData`", "`Arcane.Stream`, `Arcane.Concurrent`"], ["`Visualization`, `BI`", "`Arcane.Vitrine`, `Arcane.Analytics`"], ["`MachineLearning`, `AI`", "`Arcane.Cortex` + a ponte"], ["`Quality`, `Governance`, `Observability`", "`Arcane.Qualidade`, `Arcane.Observar`"], ["`TimeSeries`", "`Arcane.Analytics` + `Arcane.Time`"], ["`Cloud`", "**fora** — serviços, alcançáveis por `Arcane.Http`"]]}},
  {"p": "Vinte e um módulos propostos couberam em doze que já existiam mais um novo. Criar um módulo por tópico daria vinte e uma portas para o que é um assunto só — e a regra aqui é que a tabela de módulos não divirja da realidade."},
  {"h2": "O que este mapa recusa a prometer"},
  {"list": ["**Driver de banco em rede** — PostgreSQL, MySQL, Oracle, MongoDB, Redis. Cada um é um protocolo de rede, e a promessa da linguagem é zero dependência no runtime.", "**Motor distribuído** — Spark, Flink, Hadoop. São sistemas, não bibliotecas; reimplementá-los em Python daria um subconjunto pior amarrado à linguagem.", "**Aprendizado profundo** — uma rede neural sem BLAS é um brinquedo. A ponte para o `torch` é honesta; uma implementação própria não seria.", "**Conectores de nuvem** — S3, GCS, Azure. São APIs HTTP, e `Arcane.Http` fala com elas; um cliente oficial de cada uma é manutenção sem fim.", "**Avro e ORC** — formatos de um ecossistema que a linguagem não fala. Parquet existe porque ele é a fronteira que um lago de dados realmente usa."]},
  {"callout": {"tipo": "dica", "titulo": "Como este mapa não envelhece", "texto": "As linhas marcadas **nativo** citam símbolos, e símbolo que sai da biblioteca quebra `tests/test_estabilidade.py`. As linhas **fora** citam o motivo, e não a falta — é o motivo que envelhece devagar."}},
  {"h2": "Por onde seguir"},
  {"cards": [{"href": "/docs/dados/quadro", "title": "O Quadro", "desc": "a tabela, verbo por verbo"}, {"href": "/docs/dados/verbos", "title": "Os verbos do pipeline", "desc": "a sintaxe nativa"}, {"href": "/docs/dados", "title": "Análise de dados", "desc": "o caminho de um conjunto até a resposta"}, {"href": "/docs/dados/etl", "title": "ETL", "desc": "idempotência, falha parcial e reprocessamento"}]},
];

const headings = [{ id: '1-fundamentos-e-estatistica-descritiva', text: "1 — Fundamentos e estatística descritiva", level: 2 as const }, { id: '2-manipulacao-de-dados', text: "2 — Manipulação de dados", level: 2 as const }, { id: '3-e-4-etl-e-elt', text: "3 e 4 — ETL e ELT", level: 2 as const }, { id: '5-engenharia-de-dados', text: "5 — Engenharia de dados", level: 2 as const }, { id: '6-7-e-19-sql-data-warehouse-data-lake-e-lakehouse', text: "6, 7 e 19 — SQL, Data Warehouse, Data Lake e Lakehouse", level: 2 as const }, { id: '8-e-9-big-data-e-tempo-real', text: "8 e 9 — Big Data e tempo real", level: 2 as const }, { id: '10-e-25-visualizacao-e-bi', text: "10 e 25 — Visualização e BI", level: 2 as const }, { id: '11-12-e-21-data-science-ia-e-series-temporais', text: "11, 12 e 21 — Data Science, IA e séries temporais", level: 2 as const }, { id: '15-23-24-26-e-27-qualidade-perfil-limpeza-observabilidade-e-governanca', text: "15, 23, 24, 26 e 27 — Qualidade, perfil, limpeza, observabilidade e governança", level: 2 as const }, { id: '28-e-29-testes-e-desempenho', text: "28 e 29 — Testes e desempenho", level: 2 as const }, { id: '30-a-sintaxe-que-o-documento-esbocou', text: "30 — A sintaxe que o documento esboçou", level: 2 as const }, { id: '31-os-modulos-propostos-e-onde-eles-foram-parar', text: "31 — Os módulos propostos, e onde eles foram parar", level: 2 as const }, { id: 'o-que-este-mapa-recusa-a-prometer', text: "O que este mapa recusa a prometer", level: 2 as const }, { id: 'por-onde-seguir', text: "Por onde seguir", level: 2 as const }];

export default function Pagina() {
  return (
    <DocPage
      title={"O mapa do ecossistema de dados"}
      description={"As 32 áreas de dados, cruzadas com o que a linguagem tem: o que é nativo, o que atravessa a ponte, e o que não existe por decisão."}
      href={"/docs/dados/mapa"}
      headings={headings}
    >
      <Renderer blocos={blocos} />
    </DocPage>
  );
}
