// GERADO por 'site/scripts/gerar_conteudo.py'. Nao edite aqui.
// A fonte e 'site/scripts/conteudo/compilador_interno.py' — mude la e rode o gerador.

import type { Metadata } from 'next';
import type { Bloco } from '@/lib/content';
import { DocPage } from '@/components/Doc';
import { Renderer } from '@/components/Renderer';

export const metadata: Metadata = {
  title: "O compilador: o mapa",
  description: "Item por item da parte 7 da referência Deep Tech — pipeline, lexer, parser, AST, HIR, MIR, LIR e análise estática — cruzado com o que o DataForge tem.",
};

const blocos: Bloco[] = [
  {"p": "A sétima parte de uma referência Deep Tech abre o compilador: as oito seções vão do pipeline às análises. É a parte em que o DataForge tem **mais** do que parece — ele tem lexer, parser, AST, analisador e backend próprios — e ao mesmo tempo a primeira em que um item é honestamente **não se aplica**."},
  {"h2": "30 · Pipeline de compilação"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["fluxo de fases", "seis fases, e `dataforge ir` mostra cada uma", "[Pipeline](/docs/compilador/pipeline)"], ["type checking", "`typechecker.py` — 1752 linhas, entre o HIR e o MIR", "[Análise estática](/docs/tecnicas/analise-estatica)"], ["borrow checking", "`Arcane.Posse` mais as checagens de fluxo do `check`", "[Posse](/docs/memoria/posse)"], ["LLVM IR, machine code, linker", "**não se aplica**: o DataForge é interpretado. O backend é o compilador de fechamentos, e a última fase é chamar fechamento Python", "[Pipeline](/docs/compilador/pipeline)"]]}},
  {"h2": "31 · Lexer"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["tokenização, identificadores, keywords", "`lexer.py`; 81 palavras reservadas, e as contextuais que **não** são", "[Palavras](/docs/referencia/palavras-reservadas)"], ["literais, operadores", "inteiro, real, texto, `yes`/`no`/`void`, tupla; `~/` para divisão inteira", "[Operadores](/docs/operadores)"], ["comentários", "`//` é comentário **por padrão**, e vira divisão só quando o que segue confirma", "[Operadores](/docs/operadores)"], ["strings, interpolação", "`$\"…{expr}…\"`, com `{x:.2f}`; a string aninhada é copiada verbatim", "[Interpolação](/docs/fundamentos/interpolacao)"], ["source spans", "linha, coluna e `span` em todo nó e em todo erro — é o que desenha a seta", "[Erros](/docs/erros)"], ["erros léxicos", "`SyncError` para tab na indentação, e a mensagem diz o que fazer", "[Erros](/docs/erros)"], ["INDENT/DEDENT", "**além** da lista: o lexer emite os dois, e é deles que sai a profundidade do formatador", "[Arquitetura](/docs/referencia/arquitetura)"]]}},
  {"h2": "32 · Parser"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["recursive descent", "`parser.py`, 1941 linhas, descendente recursivo", "[Arquitetura](/docs/referencia/arquitetura)"], ["precedência, associatividade", "por nível de função (`parse_or` → `parse_and` → …)", "[Gramática](/docs/referencia/gramatica)"], ["parsing de expressões e declarações", "o conjunto todo, com a EBNF **gerada** do código", "[Gramática](/docs/referencia/gramatica)"], ["AST construction", "`ast_nodes.py` — 140 dataclasses", "[AST](/docs/compilador/pipeline)"], ["Pratt parser", "**não é** a técnica usada: a precedência é a cascata de funções. Pratt paga quando a tabela de operadores é dinâmica, e aqui ela é fixa", "—"], ["recuperação de erros", "**parcial**: o `check` continua depois de um arquivo que não compila (a superfície devolve `aberta = yes`), mas dentro de um arquivo o primeiro erro de sintaxe encerra a leitura", "—"]]}},
  {"h2": "33 · AST"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["nós de expressão e de declaração", "140 classes; `dataforge ast` e `K.arvore(fonte)`", "[Pipeline](/docs/compilador/pipeline)"], ["tipos, funções, structs, traits, generics", "`TypeDeclaration`, `ActionDeclaration`, `RecordDeclaration`, `TraitDeclaration`, `type_params`", "[Tipos](/docs/tipos/mapa)"], ["pattern matching", "oito classes de padrão, de `WildcardPattern` a `OrPattern`", "[Pattern matching](/docs/fundamentos/pattern-matching)"], ["metadados, source locations", "`line`, `column` em toda `ASTNode`; a ação sabe em que **arquivo** nasceu", "[Erros](/docs/erros)"], ["a árvore como dado", "**além** da lista: `Arcane.Macro` a entrega como vault, e a volta é conferida", "[Macros](/docs/metaprogramacao/macros)"]]}},
  {"h2": "34 · HIR"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["desugaring", "`hir.normalizar` — cinco açúcares, e oito formas que só parecem", "[HIR](/docs/compilador/hir)"], ["resolução de nomes", "`hir.resolucao` — parâmetro, local, livre, embutido, por corpo", "[HIR](/docs/compilador/hir)"], ["normalização", "é o mesmo passo: o HIR é a AST restrita ao núcleo", "[HIR](/docs/compilador/hir)"], ["expansão de macros", "roda na **carga**, no `comptime` e no decorador de macro — antes desta fase", "[comptime](/docs/metaprogramacao/comptime)"], ["representação semântica", "o HIR usa as **mesmas classes** da AST, de propósito: é o que permite provar a equivalência **rodando** os dois", "[HIR](/docs/compilador/hir)"]]}},
  {"h2": "35 · MIR"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["basic blocks, controle de fluxo", "`mir.construir` — um corpo por ação, arestas rotuladas", "[MIR](/docs/compilador/mir)"], ["dataflow analysis", "vivacidade, definição em todo caminho, propagação de constante", "[Análises](/docs/compilador/analises)"], ["borrow checking", "`posse-movida`, `emprestimo-escapa`, `recurso-vazado` — no `typechecker`, sobre a árvore", "[Posse](/docs/memoria/posse)"], ["ownership analysis", "a mesma família, e `escapam` responde quem mais alcança o valor", "[Análises](/docs/compilador/analises)"], ["lifetime analysis", "**não há tempo de vida nomeado** (`'a`): o coletor do Python responde pela memória, e um `'a` sem nada para provar seria cerimônia", "—"], ["otimizações intermediárias", "**não há**: o MIR é para **analisar**, não para reescrever. O ganho de velocidade vem do compilador de fechamentos, medido em 1,5× a 1,8×", "—"]]}},
  {"h2": "36 · LIR"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["lowering", "a árvore vira fechamentos Python, uma vez", "[LIR](/docs/compilador/analises)"], ["operações primitivas", "cada fechamento delega aos **mesmos** auxiliares do interpretador (`_operar`, `_comparar`) — não há segunda semântica", "[Arquitetura](/docs/referencia/arquitetura)"], ["preparação para backend", "é o backend: `dataforge ir --fase=lir` diz o que compilou e o que recuou", "[LIR](/docs/compilador/analises)"], ["calling conventions, ABI lowering", "existem, mas **só na fronteira com o C**: `Arcane.C` declara a assinatura e o `ctypes` aplica a ABI da plataforma", "[FFI](/docs/ffi/c)"], ["representação de memória", "o mesmo: `C.estrutura` dá tamanho, alinhamento e deslocamento de verdade", "[FFI](/docs/ffi/c)"], ["registradores, spilling", "**não se aplica**", "—"]]}},
  {"h2": "37 · Análise estática"},
  {"table": {"head": ["Item", "No DataForge", "Onde"], "rows": [["type checking", "`dataforge check`, e ele **atravessa arquivos**: aridade, tipo de parâmetro e de retorno pela fronteira do `adopt`", "[Análise estática](/docs/tecnicas/analise-estatica)"], ["dataflow analysis", "as cinco análises do MIR", "[Análises](/docs/compilador/analises)"], ["reachability", "`alcancaveis`, mais o `unreachable` depois de `yield`/`halt`/`skip` e o `point-inalcancavel`", "[Análises](/docs/compilador/analises)"], ["dead code analysis", "`unused-variable`, `unused-import`, `unused-parameter` no `lint`", "[Lint](/docs/cli/lint)"], ["constant propagation", "`constantes`, e o `check` já provava `indice-fora-do-alcance` e `chave-ausente` a partir de literal", "[Análises](/docs/compilador/analises)"], ["escape analysis", "`escapam`, com quatro motivos", "[Análises](/docs/compilador/analises)"], ["borrow / lifetime analysis", "a família da posse; tempo de vida nomeado não existe", "[Posse](/docs/memoria/posse)"], ["static assertions", "`assert` dentro de `comptime` — o `check` o **executa** e acusa `comptime-falhou`", "[comptime](/docs/metaprogramacao/comptime)"], ["formal verification hooks", "`expects`, `promises`, `invariant` são contratos **cobrados em execução**, e `--plugin=` deixa acoplar uma regra própria. Prova formal (SMT, refinamento provado) **não existe**", "[Contratos](/docs/oop/contratos)"]]}},
  {"h2": "O resumo honesto"},
  {"p": "Das oito seções, seis estão cobertas de ponta a ponta — e duas delas (HIR e MIR) passaram a existir como **representação inspecionável**, não só como código escondido dentro do analisador. O que fica de fora é o que depende de gerar código de máquina: LLVM, registradores, linker. Não é uma lacuna a preencher: é o que a escolha de ser interpretado significa, e o teto dessa técnica já está medido em ~6,5×."},
  {"callout": {"tipo": "nota", "titulo": "O que esta parte entregou de novo à linguagem", "texto": "Um comando (`dataforge ir`), um módulo (`Arcane.Compilador`), duas representações (`hir.py`, `mir.py`), cinco análises de fluxo e **um aviso que o `check` não sabia dar**: o nome que só um ramo define. Zero falso alarme nos 387 arquivos do repositório — e nove casos que o filtro de nome externo cala, todos medidos."}},
];

const headings = [{ id: '30-pipeline-de-compilacao', text: "30 · Pipeline de compilação", level: 2 as const }, { id: '31-lexer', text: "31 · Lexer", level: 2 as const }, { id: '32-parser', text: "32 · Parser", level: 2 as const }, { id: '33-ast', text: "33 · AST", level: 2 as const }, { id: '34-hir', text: "34 · HIR", level: 2 as const }, { id: '35-mir', text: "35 · MIR", level: 2 as const }, { id: '36-lir', text: "36 · LIR", level: 2 as const }, { id: '37-analise-estatica', text: "37 · Análise estática", level: 2 as const }, { id: 'o-resumo-honesto', text: "O resumo honesto", level: 2 as const }];

export default function Pagina() {
  return (
    <DocPage
      title={"O compilador: o mapa"}
      description={"Item por item da parte 7 da referência Deep Tech — pipeline, lexer, parser, AST, HIR, MIR, LIR e análise estática — cruzado com o que o DataForge tem."}
      href={"/docs/compilador/mapa"}
      headings={headings}
    >
      <Renderer blocos={blocos} />
    </DocPage>
  );
}
