# -*- coding: utf-8 -*-
"""El catálogo en español.

GERADO por 'scripts/gerar_idioma_es.py' a partir dos PADROES do
'pt.py' — eles sao a metade que nao pode divergir entre dois catalogos:
um regex copiado a mao casaria 'quase', e 'quase' aqui quer dizer uma
mensagem que sai em ingles sem ninguem entender por que.

As traducoes sao escritas a mao, no gerador. Nao edite este arquivo.
"""

INTEIRAS = (
    ("'(?P<n>.+)' is not defined\\.",
     "'{n}' no está definido."),
    ("'(?P<n>.+)' is a reserved keyword and cannot be assigned to\\. Pick another name\\.",
     "'{n}' es una palabra reservada y no puede recibir un valor. Elija otro nombre."),
    ("'(?P<n>.+)' is steady and cannot be reassigned\\.",
     "'{n}' es steady y no puede ser reasignado."),
    ("'(?P<n>.+)' was read before it was assigned\\.",
     "'{n}' fue leído antes de recibir un valor."),
    ('Key \\"(?P<k>.*)\\" is not in this vault\\.',
     'La clave "{k}" no está en este vault.'),
    ('Index (?P<i>-?\\d+) is out of range for a cluster of (?P<n>\\d+) items?\\.',
     'El índice {i} está fuera del alcance de un cluster de {n} elemento(s).'),
    ('A (?P<t>\\w+) cannot be indexed\\.',
     'Un {t} no acepta índice.'),
    ('An (?P<t>\\w+) cannot be indexed\\.',
     'Un {t} no acepta índice.'),
    ('Cannot cycle over (?P<t>\\w+): expected a Cluster, Vault or String',
     'No se puede recorrer un {t}: se esperaba Cluster, Vault o String'),
    ('The (?P<t>\\w+) is empty\\.',
     'El {t} está vacío.'),
    ('Division by zero\\.',
     'División por cero.'),
    ('Cannot add Void to text\\.',
     'No se suma Void a un texto.'),
    ("'(?P<op>.+)' between an? (?P<a>\\w+) and an? (?P<b>\\w+) is not defined\\.",
     "'{op}' entre {a} y {b} no está definido."),
    ("'(?P<op>.+)' between an? (?P<a>\\w+) and an? (?P<b>\\w+) has no answer\\.",
     "'{op}' entre {a} y {b} no tiene respuesta."),
    ("'(?P<op>.+)' between a Decimal and a Float is refused",
     "'{op}' entre un Decimal y un Float se rechaza"),
    ('Cannot add (?P<a>\\w+) and (?P<b>\\w+)',
     'No se suma {a} con {b}'),
    ('Cannot multiply (?P<a>\\w+) by (?P<b>\\w+)',
     'No se multiplica {a} por {b}'),
    ("action '(?P<n>.+)' is missing argument\\(s\\): (?P<q>.+)",
     "a la acción '{n}' le falta(n) el/los argumento(s): {q}"),
    ("action '(?P<n>.+)' takes (?P<e>\\d+) argument\\(s\\) but (?P<d>\\d+) (?:was|were) given",
     "la acción '{n}' recibe {e} argumento(s), y se pasaron {d}"),
    ("action '(?P<n>.+)' got an unexpected argument '(?P<a>.+)'",
     "la acción '{n}' recibió un argumento que no conoce: '{a}'"),
    ("Call stack exceeded (?P<n>\\d+) frames in '(?P<f>.+)'\\.",
     "La pila de llamadas pasó de {n} marcos en '{f}'."),
    ("Record '(?P<r>.+)' has no field or method '(?P<m>.+)'\\. It has: (?P<tem>.*)",
     "El record '{r}' no tiene el campo ni el método '{m}'. Tiene: {tem}"),
    ("Record '(?P<r>.+)' has no field '(?P<m>.+)'",
     "El record '{r}' no tiene el campo '{m}'"),
    ("Record '(?P<r>.+)' has no field\\(s\\): (?P<q>.+)",
     "El record '{r}' no tiene el/los campo(s): {q}"),
    ('Record \'(?P<r>.+)\' is immutable: cannot assign to \'(?P<m>.+)\'\\. Build a changed copy with \\"(?P<forma>.+)\\"\\.',
     'El record \'{r}\' es inmutable: no se asigna a \'{m}\'. Haga una copia modificada con "{forma}".'),
    ("Record '(?P<r>.+)' is missing field\\(s\\): (?P<q>.+)",
     "Al record '{r}' le falta(n) el/los campo(s): {q}"),
    ("'(?P<b>.+)' has no member '(?P<m>.+)'",
     "'{b}' no tiene el miembro '{m}'"),
    ("Enum '(?P<e>.+)' has no member '(?P<m>.+)'\\. Members: (?P<tem>.*)",
     "El enum '{e}' no tiene el miembro '{m}'. Miembros: {tem}"),
    ("Cannot access member '(?P<m>.+)' on (?:an? )?(?P<t>.+?)\\.",
     "No se accede al miembro '{m}' en {t}."),
    ("Cannot read '(?P<m>.+)': the value is Void\\.",
     "No se lee '{m}': el valor es void."),
    ("module '(?P<mod>.+)' has no '(?P<m>.+)'\\.?",
     "el módulo '{mod}' no tiene '{m}'"),
    ("Cannot call '(?P<n>.+)': the value is Void\\.",
     "No se llama a '{n}': el valor es void."),
    ("Cannot call method '(?P<n>.+)' on (?P<t>.+)\\.",
     "No se llama al método '{n}' en {t}."),
    ('(?P<t>\\w+) is not callable\\.',
     '{t} no es invocable.'),
    ('Unexpected token: (?P<t>\\w+) \\((?P<v>.*)\\)',
     'Token inesperado: {t} ({v})'),
    ('Expected (?P<q>.+) after (?P<onde>.+)',
     'Se esperaba {q} después de {onde}'),
    ('Expected (?P<q>.+)',
     'Se esperaba {q}'),
    ('Tabs are not allowed for indentation\\.',
     'La tabulación no se acepta en la sangría.'),
    ('Circular import detected: (?P<cadeia>.+)',
     'Import circular: {cadeia}'),
    ('(?P<w>.+) declared as (?P<d>(?:Cluster|Vault|Set)<.+>), but (?P<onde>.+) is (?P<o>\\w+)(?P<resto>(?: — .*)?)',
     '{w} tiene el tipo {d}, pero {onde} es {o}{resto}'),
    ('(?P<w>.+) declared as (?P<d>(?:Cluster|Vault|Set)<.+>) but got (?P<o>\\w+)',
     '{w} tiene el tipo {d}, y recibió {o}'),
    ('(?P<c>(?:Cluster|Vault|Set)<.+>) only holds (?P<t>.+), and (?P<op>.+) got (?P<o>\\w+)\\.',
     '{c} solo guarda {t}, y {op} recibió {o}.'),
    ('(?P<c>(?:Cluster|Vault|Set)<.+>) cannot hold (?P<o>\\w+): (?P<r>.+) is (?P<o2>\\w+)',
     '{c} no guarda {o}: {r} es {o2}'),
    ("'(?P<b>\\w+)<…>' is not a collection type: only Cluster<T>, Vault<K, V> and Set<T> declare the type of what is inside\\. Annotate as '(?P<b2>\\w+)'\\.",
     "'{b}<…>' no es una colección: solo Cluster<T>, Vault<K, V> y Set<T> declaran el tipo de lo que hay dentro. Anótelo como '{b2}'."),
    ("(?P<f>(?:Cluster|Vault|Set)<[^>]+>) takes one type — got (?P<n>\\d+) in '(?P<t>.+)'\\.",
     "{f} lleva un tipo — y '{t}' tiene {n}."),
    ("(?P<f>Vault<K, V>) takes two types: the key and the value — got (?P<n>\\d+) in '(?P<t>.+)'\\.",
     "{f} lleva dos tipos, la clave y el valor — y '{t}' tiene {n}."),
    ('Declared as (?P<d>\\w+) but the value is (?P<o>\\w+)',
     'Declarado como {d}, y el valor es {o}'),
    ("Parameter '(?P<p>.+)' of '(?P<f>.+)' expects (?P<d>\\w+) but got (?P<o>\\w+)",
     "El parámetro '{p}' de '{f}' espera {d}, y recibió {o}"),
    ('Unreachable code: the block already ended above',
     'Código inalcanzable: el bloque ya terminó arriba'),
    ("Variable '(?P<n>.+)' is assigned but never read",
     "La variable '{n}' recibe un valor y nunca se lee"),
    ("'(?P<n>.+)' was declared as (?P<d>.+), and this assigns (?P<o>.+)",
     "'{n}' fue declarado como {d}, y esta asignación es {o}"),
    ("Field '(?P<c>.+)' of '(?P<b>.+)' is declared as (?P<d>.+), and this assigns (?P<o>.+)",
     "El campo '{c}' de '{b}' fue declarado como {d}, y esta asignación es {o}"),
    ('Assign a (?P<d>[\\w.<>, |]+)',
     'Asigne un {d}'),
    ("'(?P<p>\\w+)' cannot leave a '(?P<b>parallel|thread)' block\\.",
     "'{p}' no puede salir de un bloque '{b}'."),
    ('(?P<n>\\d+) thread\\(s\\) failed\\. The errors? (?:is|are) shown above\\.',
     '{n} thread(s) fallaron. El error está dibujado arriba.'),
    ("'(?P<n>.+)' takes (?P<e>\\d+) argument\\(s\\), got (?P<d>\\d+)",
     "'{n}' recibe {e} argumento(s), y recibió {d}"),
)

PEDACOS = (
    ("^Module '(?P<m>[^']+)' not found\\.",
     "Módulo '{m}' no encontrado."),
    ('Looked in the standard library, next to (?P<a>\\S+), and in forge_modules/\\.',
     'Busqué en la biblioteca estándar, junto a {a} y en forge_modules/.'),
    ("No packages installed — try 'dataforge add <package>'\\.",
     "Ningún paquete instalado — pruebe 'dataforge add <paquete>'."),
    ('Standard library:',
     'Biblioteca estándar:'),
    ("Did you mean '(?P<n>[^']+)'\\?",
     "¿Quiso decir '{n}'?"),
    ('^Fields: ',
     'Campos: '),
    ('^it offers: ',
     'él ofrece: '),
    ('^declared in (?P<a>.+) line (?P<l>\\d+)$',
     'declarada en {a}, línea {l}'),
    ('^It has: ',
     'Tiene: '),
    ('^Members: ',
     'Miembros: '),
    ('Pick another name\\.?',
     'Elija otro nombre.'),
    ("^variable '(?P<n>[^']+)'",
     "la variable '{n}'"),
    ("^parameter '(?P<p>[^']+)' of action '(?P<f>[^']+)'",
     "el parámetro '{p}' de la acción '{f}'"),
    ("^return value of action '(?P<f>[^']+)'",
     "el valor devuelto por la acción '{f}'"),
    ("^field '(?P<c>[^']+)' of '(?P<b>[^']+)'",
     "el campo '{c}' de '{b}'"),
    (' declared as (?P<d>[\\w.|<>, ]+?) but got (?P<o>\\w+)$',
     ' tiene el tipo {d}, y recibió {o}'),
    ('^Assign a (?P<d>[\\w.<>, |]+), or declare a new name — an annotation holds for every assignment after it, not just the first',
     'Asigne un {d}, o use un nombre nuevo — la anotación vale para toda asignación posterior, y no solo para la primera'),
    ('the value at key (?P<k>\\S+)',
     'el valor en la clave {k}'),
    ('the value of the key (?P<k>\\S+)',
     'el valor de la clave {k}'),
    ('the key (?P<k>\\S+)',
     'la clave {k}'),
    ('the item of (?P<m>\\w+)',
     'el elemento de {m}'),
    ('the assigned (?P<o>item|value)',
     'el valor asignado'),
    ('(?<!\\w)an item(?!\\w)',
     'un elemento'),
    ('every item has to be a (?P<t>.+?)(?:;| —) (?:widen the annotation \\(Any accepts everything\\) or fix the value|fix the value, or widen the annotation \\(Any accepts everything\\))',
     'todo elemento tiene que ser {t} — corrija el valor, o amplíe la anotación (Any acepta todo)'),
    ('every key has to be a (?P<t>.+)',
     'toda clave tiene que ser {t}'),
    ('insert a (?P<t>.+), or widen the annotation \\(Any accepts everything\\)',
     'inserte un {t}, o amplíe la anotación (Any acepta todo)'),
    ("object of type '(?P<t>\\w+)' has no len\\(\\)",
     '{t} no tiene tamaño'),
    ('must be real number, not (?P<t>\\w+)',
     'necesita un número real, y recibió {t}'),
    ("bad operand type for abs\\(\\): '(?P<t>\\w+)'",
     'abs() no se aplica a {t}'),
    ("can't multiply sequence by non-(?P<t>\\w+)",
     'no se repite una secuencia por algo que no es {t}'),
    ("unsupported operand type\\(s\\) for (?P<op>\\S+): '(?P<a>\\w+)' and '(?P<b>\\w+)'",
     "'{op}' no se aplica entre {a} y {b}"),
    ("'(?P<op>\\S+)' not supported between instances of '(?P<a>\\w+)' and '(?P<b>\\w+)'",
     "'{op}' no se aplica entre {a} y {b}"),
    ('^first: ',
     'el primero: '),
    ('\\ba caught error \\((?P<t>\\w+)\\)',
     'un error capturado ({t})'),
    ('\\bcaught error \\((?P<t>\\w+)\\)',
     'error capturado ({t})'),
    ("to catch the error with 'handle', use 'parallel', which waits for its statements",
     "para atrapar el error con 'handle', use 'parallel', que espera las instrucciones"),
    ("each statement of 'parallel' runs in its own thread, so there is no loop or action around it to end",
     "cada instrucción de 'parallel' corre en su propio thread, y no hay bucle ni acción alrededor para terminar"),
    ("decide inside the statement, or move the loop out of 'parallel'",
     "decida dentro de la instrucción, o saque el bucle de dentro del 'parallel'"),
    ('^key read here$',
     'la clave se leyó aquí'),
    ('^nothing to read$',
     'no hay nada que leer'),
    ('^out of range$',
     'fuera del alcance'),
    ('^used here$',
     'usado aquí'),
    ('this name was never assigned in any enclosing scope',
     'este nombre nunca recibió un valor en ningún ámbito alrededor'),
    ('the vault has (?P<n>\\d+) keys?:',
     'el vault tiene {n} clave(s):'),
    ('valid indexes go from (?P<a>-?\\d+) to (?P<b>-?\\d+), or (?P<c>-?\\d+) to (?P<d>-?\\d+) from the end',
     'los índices válidos van de {a} a {b}, o de {c} a {d} desde el final'),
    ('the right side evaluated to 0',
     'el lado derecho resultó en 0'),
    ("the (?P<lado>left|right) side evaluated to 'void'",
     "el lado {lado} resultó en 'void'"),
    ("something before this returned 'void'",
     "algo antes de esto devolvió 'void'"),
    ('Only Cluster, Vault, String and record accept \\[ \\]\\.',
     'Solo Cluster, Vault, String y record aceptan [ ].'),
    ("'steady' declares a value that never changes",
     "'steady' declara un valor que nunca cambia"),
    ('use  valor \\?\\? padrao  for a fallback, or check first with  vault\\.has\\(chave\\)',
     'use  valor ?? predeterminado  para un valor por defecto, o compruebe antes con  vault.has(clave)'),
    ('use  x\\[-1\\]  for the last item',
     'use  x[-1]  para el último elemento'),
    ('guard the divisor first:',
     'proteja el divisor antes:'),
    ('assign it before using:',
     'asigne antes de usar:'),
    ("remember DataForge assigns with ':=', not '='",
     "recuerde que DataForge asigna con ':=', no con '='"),
    ('Pass a (?P<t>\\w+)',
     'Pase {t}'),
    ('Build it as ',
     'Constrúyalo como '),
    ('Call it as ',
     'Llámelo como '),
    ('use  \\?\\.  to stop safely:',
     'use  ?.  para parar con seguridad:'),
    ('or a default:',
     'o un valor por defecto:'),
    ("Remove this line or move it before the 'yield'/'halt'/'skip'",
     "Quite esta línea, o muévala antes del 'yield'/'halt'/'skip'"),
    ("Remove it, or rename it to '(?P<n>[^']+)' to say it is on purpose",
     "Quítela, o renómbrela a '{n}' para decir que es a propósito"),
    ('Check the divisor before dividing',
     'Compruebe el divisor antes de dividir'),
    ("\\(inside a 'monitor' or 'expect', so this is only a warning\\)",
     "(dentro de un 'monitor' o 'expect', por eso es solo un aviso)"),
)
